using Content.Client.UserInterface.Controls;
using Content.Shared._BlackM.XenBiology;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client._BlackM.XenBiology;

[GenerateTypedNameReferences]
public sealed partial class XenExperimentConsoleWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;

    private readonly List<XenExperimentPrototype> _experiments = [];
    private XenExperimentConsoleBoundUserInterfaceState? _state;
    private int _selectedIndex;

    public event Action<string>? StartRequested;

    public XenExperimentConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        foreach (var experiment in _prototype.EnumeratePrototypes<XenExperimentPrototype>())
            _experiments.Add(experiment);

        _experiments.Sort((left, right) => left.Level.CompareTo(right.Level));

        foreach (var experiment in _experiments)
            ExperimentSelector.AddItem(Loc.GetString(experiment.Name));

        ExperimentSelector.OnItemSelected += args =>
        {
            _selectedIndex = args.Id;
            ExperimentSelector.SelectId(args.Id);
            RefreshSelectedExperiment();
        };

        StartButton.OnPressed += _ =>
        {
            if (_experiments.Count == 0)
                return;

            StartRequested?.Invoke(_experiments[_selectedIndex].ID);
        };

        if (_experiments.Count > 0)
            ExperimentSelector.SelectId(0);

        RefreshSelectedExperiment();
    }

    public void UpdateState(XenExperimentConsoleBoundUserInterfaceState state)
    {
        _state = state;
        DataValue.Text = Loc.GetString("xen-experiment-console-ui-data-value", ("data", state.Data));
        StabilityBar.Value = state.Stability;
        StabilityValue.Text = Loc.GetString(
            "xen-experiment-console-ui-percent-value",
            ("value", (int) Math.Round(state.Stability)));
        SampleValue.Text = state.SamplePrototype == null
            ? Loc.GetString("xen-experiment-console-ui-no-sample")
            : GetEntityName(state.SamplePrototype);
        CapacitorValue.Text = state.CapacitorPrototype == null
            ? Loc.GetString("xen-experiment-console-ui-no-capacitor")
            : GetEntityName(state.CapacitorPrototype);
        CapacitorProtectionValue.Text = Loc.GetString(
            "xen-experiment-console-ui-percent-value",
            ("value", (int) Math.Round((1f - state.IncidentChanceMultiplier) * 100f)));

        RefreshSelectedExperiment();
    }

    private void RefreshSelectedExperiment()
    {
        if (_experiments.Count == 0)
        {
            StartButton.Disabled = true;
            return;
        }

        _selectedIndex = Math.Clamp(_selectedIndex, 0, _experiments.Count - 1);
        var experiment = _experiments[_selectedIndex];

        LevelValue.Text = Loc.GetString(GetLevelKey(experiment.Level));
        RewardValue.Text = Loc.GetString("xen-experiment-console-ui-reward-value", ("reward", experiment.Reward));
        DurationValue.Text = Loc.GetString(
            "xen-experiment-console-ui-duration-value",
            ("seconds", (int) experiment.Duration.TotalSeconds));
        IncidentRiskValue.Text = Loc.GetString(
            "xen-experiment-console-ui-percent-value",
            ("value", (int) Math.Round(
                experiment.IncidentChance * (_state?.IncidentChanceMultiplier ?? 1f) * 100f)));

        StartButton.Disabled = !CanStart(experiment, out var status);
        StatusValue.Text = status;
    }

    private bool CanStart(XenExperimentPrototype experiment, out string status)
    {
        if (_state == null)
        {
            status = Loc.GetString("xen-experiment-console-ui-status-syncing");
            return false;
        }

        if (_state.RunningExperiment is { } runningExperiment)
        {
            status = Loc.GetString(
                "xen-experiment-console-ui-status-running",
                ("experiment", GetExperimentName(runningExperiment)),
                ("seconds", _state.RemainingSeconds));
            return false;
        }

        if (!_state.Powered)
        {
            status = Loc.GetString("xen-experiment-console-ui-status-no-power");
            return false;
        }

        if (!_state.Connected)
        {
            status = Loc.GetString("xen-experiment-console-ui-status-no-server");
            return false;
        }

        if (_state.SamplePrototype == null)
        {
            status = Loc.GetString("xen-experiment-console-ui-status-no-sample");
            return false;
        }

        if (_state.SampleProcessed)
        {
            status = Loc.GetString("xen-experiment-console-ui-status-processed-sample");
            return false;
        }

        if (new EntProtoId(_state.SamplePrototype) != experiment.RequiredSample)
        {
            status = Loc.GetString("xen-experiment-console-ui-status-wrong-sample");
            return false;
        }

        if (_state.Stability < experiment.MinimumStability)
        {
            status = Loc.GetString("xen-experiment-console-ui-status-low-stability");
            return false;
        }

        status = Loc.GetString("xen-experiment-console-ui-status-ready");
        return true;
    }

    private string GetExperimentName(string experimentId)
    {
        return _prototype.TryIndex<XenExperimentPrototype>(experimentId, out var experiment)
            ? Loc.GetString(experiment.Name)
            : experimentId;
    }

    private string GetEntityName(EntProtoId prototypeId)
    {
        return _prototype.TryIndex<EntityPrototype>(prototypeId, out var prototype)
            ? prototype.Name
            : prototypeId.ToString();
    }

    private string GetEntityName(string prototypeId)
    {
        return GetEntityName(new EntProtoId(prototypeId));
    }

    private static string GetLevelKey(XenExperimentLevel level)
    {
        return level switch
        {
            XenExperimentLevel.Safe => "xen-experiment-console-level-safe",
            XenExperimentLevel.Standard => "xen-experiment-console-level-standard",
            XenExperimentLevel.Dangerous => "xen-experiment-console-level-dangerous",
            XenExperimentLevel.Cascade => "xen-experiment-console-level-cascade",
            _ => "xen-experiment-console-level-safe"
        };
    }
}
