using System.Globalization;
using Content.Client.UserInterface.Controls;
using Content.Shared._BlackM.Evac;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._BlackM.Evac.UI;

[GenerateTypedNameReferences]
public sealed partial class EvacConsoleMenu : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public TimeSpan? TargetTime;
    public EvacConsoleState State = EvacConsoleState.Idle;

    public event Action? OnOpen;
    public event Action? OnClose;

    public EvacConsoleMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        OpenButton.OnPressed += _ => OnOpen?.Invoke();
        CancelButton.OnPressed += _ => OnClose?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        UpdateTimer();
    }

    public void UpdateState(EvacConsoleState state, TimeSpan? targetTime, bool portalReady)
    {
        State = state;
        TargetTime = targetTime;

        StatusLabel.Text = state switch
        {
            EvacConsoleState.Idle => portalReady
                ? Loc.GetString("evac-console-status-idle")
                : Loc.GetString("evac-console-status-no-portal"),
            EvacConsoleState.Countdown => Loc.GetString("evac-console-status-countdown"),
            EvacConsoleState.Open => Loc.GetString("evac-console-status-open"),
            _ => "—"
        };

        OpenButton.Disabled = state != EvacConsoleState.Idle || !portalReady;
        CancelButton.Disabled = state == EvacConsoleState.Idle;

        UpdateTimer();
    }

    private void UpdateTimer()
    {
        if (TargetTime == null)
        {
            TimerLabel.Text = "—";
            return;
        }

        var diff = MathHelper.Max((TargetTime - _timing.CurTime) ?? TimeSpan.Zero, TimeSpan.Zero);
        TimerLabel.Text = diff.ToString(@"mm\:ss", CultureInfo.CurrentCulture);
    }
}