using Content.Client.Audio;
using Content.Shared._BlackM.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client._BlackM.Options;

[GenerateTypedNameReferences]
public sealed partial class BlackMTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public BlackMTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionPercentSlider(
            BlackMCVars.BarksVolume,
            SliderVolumeBarks,
            scale: ContentAudioSystem.BarksMultiplier);
        Control.AddOptionPercentSlider(
            BlackMCVars.BattleMusicVolume,
            SliderVolumeBattleMusic);

        var musicRadioVolume = Control.AddOptionPercentSlider(
            BlackMCVars.MusicRadioVolume,
            SliderVolumeMusicRadio);
        musicRadioVolume.ImmediateValueChanged += value => _cfg.SetCVar(BlackMCVars.MusicRadioVolume, value);

        Control.AddOptionCheckBox(BlackMCVars.EchoEnabled, EchoEnabledCheckBox);
        Control.AddOptionCheckBox(BlackMCVars.EchoStrongPreset, EchoStrongPresetCheckBox);
        Control.AddOptionCheckBox(BlackMCVars.BattleMusicEnabled, BattleMusicEnabledCheckBox);
        Control.AddOptionCheckBox(BlackMCVars.DefaultAtmosphereShaderEnabled, DefaultAtmosphereShaderCheckBox);

        Control.Initialize();
    }
}
