- type: job
  id: Surgeon
  name: job-name-surgeon
  description: job-description-surgeon
  playTimeTracker: JobSurgeon
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 0 # BlackM 54000 #15 hrs
  startingGear: SurgeonGear
  icon: "JobIconSurgeon"
  supervisors: job-supervisors-cmo
  skills: # CorvaxGoob-Skills
  - Surgery
  - MedicalEquipment
  - Butchering
  access:
  - Medical
  - Maintenance
  extendedAccess:
  - Chemistry
  special:
  - !type:AddComponentSpecial
    components:
    - type: SurgerySpeedModifier
      speedModifier: 2.5

- type: startingGear
  id: SurgeonGear
  equipment:
    belt: ClothingBeltSurgicalBoardFilled
    shoes: ClothingShoesColorWhite
    id: AccessCardHolderMedic #BlackM id
    passport: PassportBM #BlackM pass
    mask: ClothingMaskSterile

- type: chameleonOutfit
  id: SurgeonChameleonOutfit
  job: Surgeon
  equipment:
    head: ClothingHeadHatBeretMedic
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesNitrile
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    id: SurgeonPDA
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorWhite
