using Content.Client.Info;
using System.Numerics;
using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Input;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.StylesheetHelpers;

namespace Content.Client._BlackM.Rules;

/// <summary>Arrival, folder and departure presentation around the existing rules document and acceptance protocol.</summary>
[GenerateTypedNameReferences]
public sealed partial class RulesArrivalPopup : Control
{
    [Dependency] private readonly IResourceCache _resources = default!;
    private enum Stage { Starting, FadingIn, Walking, Reading, Burning, Leaving, FadingOut, Finished }
    private readonly HashSet<BoundKeyFunction> _movement = new();
    private bool _greeted;
    private Stage _stage;
    private float _elapsed;
    private float _remaining;
    private bool _hasScene;
    private bool _skipIntro;
    private string _speech = string.Empty;
    private float _speechTime;
    private int _speechLength = -1;
    private readonly StyleBoxFlat _dimmerStyle = new(Color.Black);
    public event Action? OnAcceptPressed;
    public event Action? OnQuitPressed;

    public RulesArrivalPopup()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SpeechBubble.StyleClasses.Add("speechBox");
        SpeechBubble.StyleClasses.Add("sayBox");
        CanKeyboardFocus = true;
        Background.MouseFilter = MouseFilterMode.Ignore;
        Background.PanelOverride = new StyleBoxFlat(Color.Black);
        Dimmer.PanelOverride = _dimmerStyle;
        Folder.PanelOverride = new StyleBoxFlat(Color.FromHex("#3B3C51")) { BorderColor = Color.FromHex("#67647A"), BorderThickness = new Thickness(2) };
        Paper.PanelOverride = new StyleBoxFlat(Color.FromHex("#E3E2CF")) { BorderColor = Color.FromHex("#AAA996"), BorderThickness = new Thickness(1, 1, 4, 4) };
        PhotoMount.PanelOverride = new StyleBoxFlat(Color.FromHex("#A8AAA2")) { BorderColor = Color.FromHex("#F5F2DF"), BorderThickness = new Thickness(5) };
        FolderSpine.PanelOverride = new StyleBoxFlat(Color.FromHex("#292A3B"));
        BurnEffect.Folder = Folder;
        var ink = Color.FromHex("#272B2B");
        var red = Color.FromHex("#8D2234");
        Document.DocumentTint = ink;
        var font = new VectorFont(_resources.GetResource<FontResource>("/Fonts/RobotoMono/RobotoMono-Regular.ttf"), 12);
        var heading = new VectorFont(_resources.GetResource<FontResource>("/Fonts/RobotoMono/RobotoMono-Bold.ttf"), 18);
        Folder.Stylesheet = new Stylesheet(new StyleRule[]
        {
            Element<Label>().Prop("font", font).Prop("font-color", Color.FromHex("#CDCCCE")),
            Element<Label>().Class("DossierBrand").Prop("font", heading),
            Element<PanelContainer>().Class("DossierRule").Prop("panel", new StyleBoxFlat(Color.FromHex("#777487"))),
        });
        var button = new StyleBoxFlat(Color.FromHex("#D1D0BD"))
        {
            BorderColor = ink, BorderThickness = new Thickness(1),
            ContentMarginTopOverride = 6, ContentMarginBottomOverride = 6,
            ContentMarginLeftOverride = 10, ContentMarginRightOverride = 10,
        };
        Paper.Stylesheet = new Stylesheet(new StyleRule[]
        {
            Element<Label>().Prop("font-color", ink).Prop("font", font),
            Element<RichTextLabel>().Prop("font-color", ink).Prop("font", font),
            Element<Label>().Class("DossierClassification").Prop("font-color", red).Prop("font", heading),
            Element<Label>().Class("DossierTitle").Prop("font", heading),
            Element<PanelContainer>().Class("DossierInkRule").Prop("panel", new StyleBoxFlat(ink)),
            Element<ContainerButton>().Prop("stylebox", button),
            Element<ContainerButton>().Pseudo("hover").Prop("stylebox", new StyleBoxFlat(Color.FromHex("#B8B6A4"))
            {
                BorderColor = ink, BorderThickness = new Thickness(1),
                ContentMarginTopOverride = 6, ContentMarginBottomOverride = 6,
                ContentMarginLeftOverride = 10, ContentMarginRightOverride = 10,
            }),
            Element<ContainerButton>().Pseudo("disabled").Prop("stylebox", new StyleBoxFlat(Color.FromHex("#DAD9C9"))
            {
                BorderColor = Color.FromHex("#9A9B90"), BorderThickness = new Thickness(1),
                ContentMarginTopOverride = 6, ContentMarginBottomOverride = 6,
                ContentMarginLeftOverride = 10, ContentMarginRightOverride = 10,
            }),
        });
        HandlingNotice.SetMessage(Loc.GetString("blackm-arrival-handling"), defaultColor: Color.FromHex("#CDCCCE"));
        FileSummary.SetMessage(Loc.GetString("blackm-arrival-file-summary"), defaultColor: ink);
        CoverTitle.SetMessage(Loc.GetString("blackm-arrival-cover"), defaultColor: ink);
        CoverNotice.SetMessage(Loc.GetString("blackm-arrival-cover-notice"), defaultColor: ink);
        OpenButton.OnPressed += _ => OpenDocument();
        QuitButton.OnPressed += _ => OnQuitPressed?.Invoke();
        SignButton.OnPressed += _ => Sign();
    }

    public void Initialize(float waitTime, bool skipIntro)
    {
        _remaining = Math.Max(0, waitTime);
        _skipIntro = skipIntro;
    }

    private void OpenDocument()
    {
        if (_stage is Stage.Burning or Stage.Leaving or Stage.FadingOut or Stage.Finished)
            return;
        if (_stage == Stage.Starting)
        {
            _skipIntro = true;
            return;
        }
        _movement.Clear();
        _stage = Stage.Reading;
        Folder.Visible = Document.Visible = Signature.Visible = true;
        BurnEffect.Visible = true;
        Cover.Visible = SpeechBubble.Visible = false;
        PhotoMount.Visible = Scene.Employee != null;
        Portrait.SetEntity(Scene.Employee);
        Dimmer.ModulateSelfOverride = Color.White;
        _dimmerStyle.BackgroundColor = Color.Black.WithAlpha(0.80f);
        UpdateWait();
    }

    private static bool IsMovement(BoundKeyFunction function)
    {
        return function == EngineKeyFunctions.MoveUp || function == EngineKeyFunctions.MoveDown ||
               function == EngineKeyFunctions.MoveLeft || function == EngineKeyFunctions.MoveRight;
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);
        if (IsMovement(args.Function))
        {
            if (_stage is Stage.Walking or Stage.Leaving)
                _movement.Add(args.Function);
            args.Handle();
            return;
        }
        if (args.Function != EngineKeyFunctions.UIClick ||
            _stage is not (Stage.Walking or Stage.Leaving))
            return;
        GrabKeyboardFocus();
        if (_stage == Stage.Walking && Scene.NearCheckpoint && Scene.IsCheckpointClick(args.PointerLocation.Position))
            OpenDocument();
        args.Handle();
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);
        if (!IsMovement(args.Function))
            return;
        _movement.Remove(args.Function);
        args.Handle();
    }

    protected override void KeyboardFocusExited()
    {
        base.KeyboardFocusExited();
        _movement.Clear();
    }

    private void MoveEmployee(float frameTime)
    {
        var direction = new Vector2(
            (_movement.Contains(EngineKeyFunctions.MoveRight) ? 1 : 0) - (_movement.Contains(EngineKeyFunctions.MoveLeft) ? 1 : 0),
            (_movement.Contains(EngineKeyFunctions.MoveUp) ? 1 : 0) - (_movement.Contains(EngineKeyFunctions.MoveDown) ? 1 : 0));
        Scene.MoveEmployee(direction, frameTime);
    }

    private void UpdateWait()
    {
        WaitLabel.Text = Loc.GetString("ui-rules-wait", ("time", MathF.Ceiling(_remaining)));
        WaitLabel.Visible = _remaining > 0;
        SignButton.Disabled = _remaining > 0;
    }

    private void Sign()
    {
        if (_stage != Stage.Reading || _remaining > 0)
            return;
        _stage = Stage.Burning;
        _elapsed = 0;
        _movement.Clear();
        SignButton.Disabled = true;
        SignButton.Text = Loc.GetString("blackm-arrival-signed");
        BurnEffect.Ignite();
    }

    private void LeaveCheckpoint()
    {
        _stage = Stage.Leaving;
        _elapsed = 0;
        Folder.Visible = BurnEffect.Visible = false;
        Speak("blackm-arrival-approved");
        _dimmerStyle.BackgroundColor = Color.Transparent;
        if (!_hasScene)
        {
            Finish();
            return;
        }
        Scene.OpenPassage();
        GrabKeyboardFocus();
    }

    private void Finish()
    {
        if (_stage == Stage.Finished)
            return;
        _stage = Stage.Finished;
        // Close on the next tick, never while traversing this control's FrameUpdate tree.
        Robust.Shared.Timing.Timer.Spawn(TimeSpan.Zero, () =>
        {
            if (!Disposed)
                OnAcceptPressed?.Invoke();
        });
    }

    private void Speak(string key)
    {
        _speech = Loc.GetString(key);
        _speechTime = 0;
        _speechLength = -1;
        SpeechBubble.Visible = _hasScene;
        UpdateSpeech(0);
    }

    private void UpdateSpeech(float frameTime)
    {
        if (!SpeechBubble.Visible || !Scene.TryGetSpeakerPosition(out var anchor))
            return;
        _speechTime += frameTime;
        if (_speechTime > _speech.Length / 32f + 3f)
        {
            SpeechBubble.Visible = false;
            return;
        }
        var count = Math.Min(_speech.Length, (int) (_speechTime * 32));
        if (count != _speechLength)
        {
            _speechLength = count;
            var message = new FormattedMessage();
            message.AddText(_speech[..count]);
            // Reserve the entire message layout while revealing characters.
            message.PushColor(Color.Transparent);
            message.AddText(_speech[count..]);
            message.Pop();
            Dialogue.SetMessage(message);
        }
        var width = Math.Min(330, Math.Max(1, Width - 32));
        SpeechBubble.SetWidth = width;
        LayoutContainer.SetPosition(SpeechBubble, new Vector2(
            Math.Clamp(anchor.X - width / 2, 16, Math.Max(16, Width - width - 16)),
            Math.Clamp(anchor.Y - SpeechBubble.Height - 48, 16, Math.Max(16, Height - SpeechBubble.Height - 16))));
    }

    protected override void Resized()
    {
        base.Resized();
        if (Folder != null)
        {
            Folder.SetSize = Vector2.Max(Vector2.Zero, Vector2.Min(new Vector2(1040, 780), Size - new Vector2(48, 144)));
            DossierFlap.Visible = Size.X >= 900;
            FolderSpine.Visible = DossierFlap.Visible;
            FileHeader.Visible = Size.Y >= 600;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (_hasScene && _stage is not (Stage.Walking or Stage.Leaving))
            Scene.MoveEmployee(Vector2.Zero, args.DeltaSeconds);
        UpdateSpeech(args.DeltaSeconds);
        switch (_stage)
        {
            case Stage.Starting:
                _elapsed += args.DeltaSeconds;
                if (!Scene.ProfileReady && _elapsed < 5f)
                    break;
                try
                {
                    _hasScene = Scene.TryStart();
                }
                catch (Exception exception)
                {
                    Logger.ErrorS("rules-arrival", $"Unable to load arrival scene: {exception}");
                    Scene.Release();
                }
                _stage = Stage.FadingIn;
                _elapsed = 0;
                GrabKeyboardFocus();
                if (!_hasScene || _skipIntro)
                    OpenDocument();
                break;
            case Stage.FadingIn:
                _elapsed += args.DeltaSeconds;
                _dimmerStyle.BackgroundColor = Color.Black.WithAlpha(1 - Math.Clamp(_elapsed / 1.25f, 0, 1));
                if (_elapsed >= 1.25f)
                {
                    _elapsed = 0;
                    _stage = Stage.Walking;
                }
                break;
            case Stage.Walking:
                MoveEmployee(args.DeltaSeconds);
                if (Scene.NearCheckpoint && !_greeted)
                {
                    _greeted = true;
                    Speak("blackm-arrival-guard");
                }
                break;
            case Stage.Reading:
                if (_remaining > 0)
                {
                    _remaining = Math.Max(0, _remaining - args.DeltaSeconds);
                    UpdateWait();
                }
                break;
            case Stage.Burning:
                _elapsed += args.DeltaSeconds;
                BurnEffect.Progress = Math.Clamp((_elapsed - 0.45f) / 4f, 0, 1);
                if (_elapsed >= 4.7f)
                    LeaveCheckpoint();
                break;
            case Stage.Leaving:
                _elapsed += args.DeltaSeconds;
                Scene.StepGuardAside(_elapsed / 0.8f);
                MoveEmployee(args.DeltaSeconds);
                if (Scene.InElevator)
                {
                    _stage = Stage.FadingOut;
                    _elapsed = 0;
                    _movement.Clear();
                    SpeechBubble.Visible = false;
                }
                break;
            case Stage.FadingOut:
                _elapsed += args.DeltaSeconds;
                _dimmerStyle.BackgroundColor = Color.Black.WithAlpha(Math.Clamp(_elapsed, 0, 1));
                if (_elapsed >= 1)
                    Finish();
                break;
        }
    }

    protected override void RenderChildOverride(ref ControlRenderArguments args, int childIndex, Vector2i position)
    {
        // During burning the folder is drawn only into the effect's offscreen texture.
        if (_stage == Stage.Burning && GetChild(childIndex) == Folder)
            return;
        base.RenderChildOverride(ref args, childIndex, position);
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
        {
            _stage = Stage.Finished;
            Portrait.SetEntity(null);
            OnAcceptPressed = null;
            OnQuitPressed = null;
        }
        base.Dispose(disposing);
    }
}
