// SPDX-FileCopyrightText: 2021 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Jesse Rougeau <jmaster9999@gmail.com>
// SPDX-FileCopyrightText: 2022 ZeroDayDaemon <60460608+ZeroDayDaemon@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2023 Flipp Syder <76629141+vulppine@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 12rabbits <53499656+12rabbits@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Alzore <140123969+Blackern5000@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 ArtisticRoomba <145879011+ArtisticRoomba@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Brandon Hu <103440971+Brandon-Huu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Dimastra <65184747+Dimastra@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Dimastra <dimastra@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Emisse <99158783+Emisse@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Eoin Mcloughlin <helloworld@eoinrul.es>
// SPDX-FileCopyrightText: 2024 Fildrance <fildrance@gmail.com>
// SPDX-FileCopyrightText: 2024 Firewatch <54725557+musicmanvr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 IProduceWidgets <107586145+IProduceWidgets@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 JIPDawg <51352440+JIPDawg@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 JIPDawg <JIPDawg93@gmail.com>
// SPDX-FileCopyrightText: 2024 Mervill <mervills.email@gmail.com>
// SPDX-FileCopyrightText: 2024 Moomoobeef <62638182+Moomoobeef@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Mr. 27 <koolthunder019@gmail.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 PJBot <pieterjan.briers+bot@gmail.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers@gmail.com>
// SPDX-FileCopyrightText: 2024 PopGamer46 <yt1popgamer@gmail.com>
// SPDX-FileCopyrightText: 2024 PursuitInAshes <pursuitinashes@gmail.com>
// SPDX-FileCopyrightText: 2024 QueerNB <176353696+QueerNB@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Saphire Lattice <lattice@saphi.re>
// SPDX-FileCopyrightText: 2024 ShadowCommander <10494922+ShadowCommander@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Simon <63975668+Simyon264@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Spessmann <156740760+Spessmann@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Thomas <87614336+Aeshus@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 dffdff2423 <dffdff2423@gmail.com>
// SPDX-FileCopyrightText: 2024 eoineoineoin <github@eoinrul.es>
// SPDX-FileCopyrightText: 2024 github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 lzk <124214523+lzk228@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 pa.pecherskij <pa.pecherskij@interfax.ru>
// SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 stellar-novas <stellar_novas@riseup.net>
// SPDX-FileCopyrightText: 2024 themias <89101928+themias@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Piras314 <p1r4s@proton.me>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client._BlackM.Lobby.Terminal; // BlackM
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics; // BlackM
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Log; // BlackM
using Robust.Shared.Timing; // BlackM

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;

        // BlackM start
        private const bool ShowLobbyBackground = false;

        private const bool EnableFisheye = false;

        private LobbyGuiState _state = LobbyGuiState.Default;
        private float _styleTimer;
        // BlackM end
        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            // BlackM start
            // SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            // SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);
            SetAnchorPreset(BackgroundGrid, LayoutPreset.Wide);
            SetAnchorPreset(BackgroundFx, LayoutPreset.Wide);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Scanlines, LayoutPreset.Wide);
            SetAnchorPreset(BootOverlay, LayoutPreset.Wide);

            Background.Visible = ShowLobbyBackground;
            BackgroundGrid.FillAlpha = ShowLobbyBackground ? 0.5f : 1f;
            // BlackM end

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
          //LobbyBackground.SetMarkup(Loc.GetString("")); // blackM

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);
            // BlackM start
            TerminalSounds.AttachAll(this);

            Hub.Activated += OnHubActivated;

            if (TerminalBootOverlay.WillPlay)
            {
                Menu.HoldHidden();
                Hub.HoldHidden();
                BootOverlay.Finished += StartIntro;
            }
            else
            {
                StartIntro();
            }
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            _styleTimer += args.DeltaSeconds;
            if (_styleTimer < 0.25f)
                return;

            _styleTimer = 0f;
            TerminalStyler.ApplyTree(LinkBanner, true);
            TerminalStyler.ApplyTree(DevInfoBanner, true);
            TerminalSounds.AttachAll(LinkBanner);
            TerminalSounds.AttachAll(DevInfoBanner);
        }

        protected override void EnteredTree()
        {
            base.EnteredTree();

            if (!EnableFisheye)
                return;

            try
            {
                var overlays = IoCManager.Resolve<IOverlayManager>();
                if (!overlays.HasOverlay<CrtFisheyeOverlay>())
                    overlays.AddOverlay(new CrtFisheyeOverlay());
            }
            catch (Exception e)
            {
                IoCManager.Resolve<ILogManager>().GetSawmill("blackm.fisheye")
                    .Warning($"Fisheye overlay disabled: {e.Message}");
            }
        }

        protected override void ExitedTree()
        {
            base.ExitedTree();

            var overlays = IoCManager.Resolve<IOverlayManager>();
            if (overlays.HasOverlay<CrtFisheyeOverlay>())
                overlays.RemoveOverlay<CrtFisheyeOverlay>();
        }

        private void StartIntro()
        {
            Menu.PlayIntro();
            Hub.PlayIntro();
            TerminalHeader.Reveal(">> " + Loc.GetString("blackm-term-header"));
        }

        private void OnHubActivated(string? tabTitleId)
        {
            ReadyButton.Pressed = false;
            _consoleHost.ExecuteCommand("toggleready False");

            SwitchState(LobbyGuiState.CharacterSetup);

            if (tabTitleId == null)
                return;

            foreach (var child in CharacterSetupState.Children)
            {
                if (child is CharacterSetupGui setupGui)
                    setupGui.OpenSection(tabTitleId);
            }
            // BlackM end
        }

        public void SwitchState(LobbyGuiState state)
        {
            // BlackM start
            var previous = _state;
            _state = state;
            // BlackM end
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    // BlackM start
                    if (previous == LobbyGuiState.CharacterSetup)
                    {
                        TerminalSounds.Play(TerminalSounds.Close);
                        Menu.PlayIntro();
                        Hub.PlayIntro();
                    }
                    // BlackM end
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
                    // BlackM start
                    if (previous != LobbyGuiState.CharacterSetup)
                    {
                        TerminalSounds.Play(TerminalSounds.Open);

                        foreach (var child in CharacterSetupState.Children)
                        {
                            if (child is CharacterSetupGui setupGui)
                                setupGui.PlayIntro();
                        }
                    }
                    // BlackM end

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}