- type: ghostRole
  id: HECUSoldier
  name: ghost-role-name-hecu
  description: ghost-role-description-hecu
  rules: ghost-role-rules-hecu
  roleType: TeamAntagonist
  entityPrototype: MobHumanHECUGhostRole

- type: entity
  save: false
  name: HECU Soldier
  parent: MobHumanHECU
  id: MobHumanHECUGhostRole
  categories: [ HideSpawnMenu ]
  components:
  - type: GhostTakeoverAvailable
  - type: Loadout
    prototypes: [ HECUGhostLoadout ]

- type: startingGear
  id: HECUGhostLoadout
  equipment:
    outerClothing: ClothingArmorHecuUnit
    head: ClothingHeadHelmetBasicHecu
    jumpsuit: ClothingUniformJumpsuitHecu
    mask: ClothingMaskGasHECU
    shoes: ClothingShoesBootsJack
    back: ClothingBackpackMerc
    id: BmesaHecuPda
    ears: ClothingHeadsetAltCentCom
    hand: WeaponSubMachineGunDrozd
    gloves: ClothingHandsGlovesMercFingerless
  storage:
    back:
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - MagazinePistolSubMachineGun
    - Brutepack