using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Shared._BlackM.Ams;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._BlackM.Ams;

[GenerateTypedNameReferences]
public sealed partial class AmsWindow : DefaultWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private readonly SpriteSystem _spriteSystem;

    public event Action? OnLaunchPressed;

    private EntityUid _owner;

    private const string PartsRsiPath = "/Textures/_BlackM/Objects/ams_parts.rsi";

    private static readonly Color ColorAccent = new(0.42f, 0.72f, 0.78f);
    private static readonly Color ColorInactive = new(0.46f, 0.47f, 0.50f);
    private static readonly Color ColorDanger = new(0.80f, 0.36f, 0.38f);

    private static readonly Color ColorSyncing = ColorAccent;
    private static readonly Color ColorReady = ColorAccent;
    private static readonly Color ColorActive = ColorAccent;
    private static readonly Color ColorUsed = ColorDanger;

    private static readonly Color PanelBg = new(0.10f, 0.095f, 0.09f);
    private static readonly Color PanelBgAlt = new(0.13f, 0.125f, 0.12f);
    private static readonly Color HairlineColor = new(0.26f, 0.25f, 0.24f);

    private static readonly (string SlotId, string LabelKey, string IconState)[] SlotOrder =
    {
        ("ams_part_core", "ams-ui-part-core", "core"),
        ("ams_part_coil", "ams-ui-part-coil", "coil"),
        ("ams_part_lens", "ams-ui-part-lens", "lens"),
        ("ams_part_cell", "ams-ui-part-cell", "cell"),
        ("ams_part_stabilizer", "ams-ui-part-stabilizer", "stabilizer"),
        ("ams_part_casing", "ams-ui-part-casing", "casing"),
    };

    private readonly Dictionary<string, PanelContainer> _slotPanels = new();
    private readonly Dictionary<string, PanelContainer> _slotStrips = new();
    private readonly Dictionary<string, TextureRect> _slotIcons = new();
    private readonly Dictionary<string, ProgressBar> _slotCalBars = new();

    public AmsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entMan.System<SpriteSystem>();

        StatusPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = PanelBg,
            BorderColor = ColorInactive,
            BorderThickness = new Thickness(1, 1, 1, 3),
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4,
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
        };

        ColumnDivider.PanelOverride = new StyleBoxFlat { BackgroundColor = HairlineColor };

        foreach (var (slotId, labelKey, iconState) in SlotOrder)
        {
            var strip = new PanelContainer
            {
                MinSize = new Vector2(0, 3),
                PanelOverride = new StyleBoxFlat { BackgroundColor = ColorInactive },
            };

            var icon = new TextureRect
            {
                Texture = GetPartTexture(iconState),
                TextureScale = new Vector2(2f, 2f),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };

            var label = new Label
            {
                Text = Loc.GetString(labelKey),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                StyleClasses = { "LabelSubText" },
            };

            var calBar = new ProgressBar
            {
                MinValue = 0,
                MaxValue = 1,
                Value = 0,
                MinHeight = 6,
                HorizontalExpand = true,
                Visible = false,
            };

            var iconLabelBox = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                SeparationOverride = 4,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                VerticalExpand = true,
                Children = { icon, label, calBar },
            };

            var body = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Children = { strip, iconLabelBox },
            };

            var panel = new PanelContainer
            {
                MinSize = new Vector2(112, 88),
                PanelOverride = BuildSlotStyle(SlotVisualState.Empty),
                Children = { body },
            };

            _slotPanels[slotId] = panel;
            _slotStrips[slotId] = strip;
            _slotIcons[slotId] = icon;
            _slotCalBars[slotId] = calBar;
            SlotsGrid.AddChild(panel);
        }

        LaunchButton.OnPressed += _ => OnLaunchPressed?.Invoke();
    }

    private enum SlotVisualState
    {
        Empty,
        Calibrating,
        Calibrated,
    }

    private static StyleBoxFlat BuildSlotStyle(SlotVisualState state)
    {
        return state switch
        {
            SlotVisualState.Calibrated => new StyleBoxFlat
            {
                BackgroundColor = new Color(0.12f, 0.17f, 0.18f),
                BorderColor = ColorAccent,
                BorderThickness = new Thickness(1),
                ContentMarginTopOverride = 0,
                ContentMarginBottomOverride = 4,
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
            },
            SlotVisualState.Calibrating => new StyleBoxFlat
            {
                BackgroundColor = new Color(0.12f, 0.15f, 0.155f),
                BorderColor = ColorAccent * new Color(1f, 1f, 1f, 0.65f),
                BorderThickness = new Thickness(1),
                ContentMarginTopOverride = 0,
                ContentMarginBottomOverride = 4,
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
            },
            _ => new StyleBoxFlat
            {
                BackgroundColor = PanelBgAlt,
                BorderColor = new Color(0.30f, 0.29f, 0.28f),
                BorderThickness = new Thickness(1),
                ContentMarginTopOverride = 0,
                ContentMarginBottomOverride = 4,
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
            },
        };
    }

    private Texture? GetPartTexture(string state)
    {
        try
        {
            var specifier = new SpriteSpecifier.Rsi(new ResPath(PartsRsiPath), state);
            return _spriteSystem.Frame0(specifier);
        }
        catch
        {
            return null;
        }
    }

    public void SetEntity(EntityUid uid)
    {
        _owner = uid;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_entMan.TryGetComponent<AmsComponent>(_owner, out var ams))
            return;

        var statusColor = ams.Status switch
        {
            AmsStatus.Inactive => ColorInactive,
            AmsStatus.Synchronizing => ColorSyncing,
            AmsStatus.Ready => ColorReady,
            AmsStatus.Active => ColorActive,
            AmsStatus.Used => ColorUsed,
            _ => ColorInactive,
        };

        StatusLabel.Text = ams.Status switch
        {
            AmsStatus.Inactive => Loc.GetString("ams-ui-status-inactive"),
            AmsStatus.Synchronizing => Loc.GetString("ams-ui-status-syncing"),
            AmsStatus.Ready => Loc.GetString("ams-ui-status-ready"),
            AmsStatus.Active => Loc.GetString("ams-ui-status-active"),
            AmsStatus.Used => Loc.GetString("ams-ui-status-used"),
            _ => string.Empty,
        };
        StatusLabel.FontColorOverride = statusColor;

        StatusDot.PanelOverride = new StyleBoxFlat { BackgroundColor = statusColor };

        if (StatusPanel.PanelOverride is StyleBoxFlat statusBox)
            statusBox.BorderColor = statusColor;

        ChargeBar.Value = ams.EnergyCharge;
        ChargePercentLabel.Text = $"{(int) (ams.EnergyCharge * 100)}%";

        if (ams.Status == AmsStatus.Active && ams.ActiveEndTime.HasValue)
        {
            var remaining = ams.ActiveEndTime.Value - _timing.CurTime;
            TimeLabel.Text = remaining > TimeSpan.Zero
                ? Loc.GetString("ams-ui-time-remaining", ("time", (int) remaining.TotalSeconds))
                : string.Empty;
        }
        else
        {
            TimeLabel.Text = string.Empty;
        }

        var now = _timing.CurTime;

        foreach (var (slotId, _, _) in SlotOrder)
        {
            SlotVisualState visual;
            if (ams.CalibratedSlots.Contains(slotId))
                visual = SlotVisualState.Calibrated;
            else if (ams.FilledSlots.Contains(slotId))
                visual = SlotVisualState.Calibrating;
            else
                visual = SlotVisualState.Empty;

            _slotPanels[slotId].PanelOverride = BuildSlotStyle(visual);
            _slotStrips[slotId].PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = visual switch
                {
                    SlotVisualState.Calibrated => ColorReady,
                    SlotVisualState.Calibrating => ColorSyncing,
                    _ => new Color(0.32f, 0.31f, 0.30f),
                },
            };
            _slotIcons[slotId].Modulate = visual == SlotVisualState.Empty
                ? new Color(1f, 1f, 1f, 0.35f)
                : Color.White;

            var calBar = _slotCalBars[slotId];
            if (visual == SlotVisualState.Calibrating && ams.CalibrationStartTimes.TryGetValue(slotId, out var startTime))
            {
                var elapsed = (float) (now - startTime).TotalSeconds;
                var progress = ams.CalibrationDuration > 0f
                    ? Math.Clamp(elapsed / ams.CalibrationDuration, 0f, 1f)
                    : 1f;

                calBar.Visible = true;
                calBar.Value = progress;
            }
            else
            {
                calBar.Visible = false;
            }
        }

        var canStartSync = ams.Status == AmsStatus.Inactive && ams.AllPartsInserted;
        var canActivate = ams.Status == AmsStatus.Ready;
        var launchEnabled = !ams.HasBeenUsed && (canStartSync || canActivate);

        LaunchButton.Disabled = !launchEnabled;
        LaunchButton.Text = ams.Status switch
        {
            AmsStatus.Ready => Loc.GetString("ams-ui-launch-button"),
            _ => Loc.GetString("ams-ui-sync-button"),
        };

        var buttonTint = launchEnabled
            ? ColorAccent
            : new Color(0.55f, 0.55f, 0.55f, 0.6f);

        LaunchButton.Modulate = buttonTint;
    }
}