using System;
using Content.Shared._BlackM.Portal;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._BlackM.Portal;

[GenerateTypedNameReferences]
public sealed partial class EvacPortalWindow : FancyWindow
{
    public event Action? OnLaunchPressed;
    public event Action? OnTeleportPressed;

    private EvacPortalBuiState? _lastState;

    public EvacPortalWindow()
    {
        RobustXamlLoader.Load(this);

        LaunchButton.OnPressed += _ => OnLaunchPressed?.Invoke();
        TeleportButton.OnPressed += _ => OnTeleportPressed?.Invoke();
    }

    public void UpdateState(EvacPortalBuiState state)
    {
        _lastState = state;

        // status
        StatusLabel.Text = state.Status switch
        {
            EvacPortalStatus.Inactive      => Loc.GetString("evac-portal-status-inactive"),
            EvacPortalStatus.Synchronizing => Loc.GetString("evac-portal-status-synchronizing"),
            EvacPortalStatus.Ready         => Loc.GetString("evac-portal-status-ready"),
            EvacPortalStatus.Active        => Loc.GetString("evac-portal-status-active"),
            EvacPortalStatus.Used          => Loc.GetString("evac-portal-status-used"),
            _                              => "???",
        };

        StatusLabel.SetOnlyStyleClass(state.Status switch
        {
            EvacPortalStatus.Inactive      => "LabelSubText",
            EvacPortalStatus.Synchronizing => "LabelSecondary",
            EvacPortalStatus.Ready         => "LabelGood",
            EvacPortalStatus.Active        => "LabelGood",
            EvacPortalStatus.Used          => "LabelBad",
            _                              => "LabelSubText",
        });

        // energy
        EnergyBar.Value = state.EnergyCharge;
        EnergyLabel.Text = $"{(int)(state.EnergyCharge * 100)}%";

        // launch
        // sync lock button
        LaunchButton.Disabled = state.Status is
            EvacPortalStatus.Synchronizing or
            EvacPortalStatus.Active or
            EvacPortalStatus.Used;

        LaunchButton.Text = state.Status switch
        {
            EvacPortalStatus.Inactive      => Loc.GetString("evac-portal-button-start-sync"),
            EvacPortalStatus.Synchronizing => Loc.GetString("evac-portal-button-syncing"),
            EvacPortalStatus.Ready         => Loc.GetString("evac-portal-button-launch"),
            EvacPortalStatus.Active        => Loc.GetString("evac-portal-button-active"),
            EvacPortalStatus.Used          => Loc.GetString("evac-portal-button-used"),
            _                              => "...",
        };

        // teleport button
        // portal work
        TeleportButton.Visible = state.Status is EvacPortalStatus.Active;
        TeleportButton.Disabled = state.Status is not EvacPortalStatus.Active;

        UpdateTimer(state);
    }

    private void UpdateTimer(EvacPortalBuiState state)
    {
        if (!state.CountdownEnd.HasValue)
        {
            TimerLabel.Visible = false;
            TimerHeaderLabel.Visible = false;
            return;
        }

        TimerLabel.Visible = true;
        TimerHeaderLabel.Visible = true;

        var remaining = state.CountdownEnd.Value - IoCManager.Resolve<IGameTiming>().CurTime;
        if (remaining < TimeSpan.Zero)
            remaining = TimeSpan.Zero;

        TimerLabel.Text = $"{(int)remaining.TotalMinutes:D2}:{remaining.Seconds:D2}";

        TimerHeaderLabel.Text = state.Status == EvacPortalStatus.Synchronizing
            ? Loc.GetString("evac-portal-timer-sync")
            : Loc.GetString("evac-portal-timer-active");
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_lastState != null)
            UpdateTimer(_lastState);
    }
}