using Content.Shared._BlackM.DiscordAuth;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Utility;

namespace Content.Client._BlackM.DiscordAuth;

[GenerateTypedNameReferences]
public sealed partial class DiscordAuthGui : Control
{
    [Dependency] private Content.Corvax.Interfaces.Client.IClientDiscordAuthManager _discordAuthManager = default!;
    [Dependency] private IClientConsoleHost _consoleHost = default!;
    [Dependency] private INetManager _netManager = default!;

    private const string DiscordServerInviteUrl = "https://discord.gg/8bvmPnkTPM";

    public DiscordAuthGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        if (!_discordAuthManager.IsOpt)
        {
            ByPassBtn.Visible = false;
        }
        else
        {
            ByPassBtn.OnPressed += (_) =>
            {
                _discordAuthManager.ByPass();
            };
        }

        QuitButton.OnPressed += (_) =>
        {
            _consoleHost.ExecuteCommand("quit");
        };

        OpenUrlButton.OnPressed += (_) =>
        {
            if (_discordAuthManager.AuthUrl != string.Empty)
            {
                IoCManager.Resolve<IUriOpener>().OpenUri(_discordAuthManager.AuthUrl);
            }
        };

        OpenServerButton.OnPressed += (_) =>
        {
            IoCManager.Resolve<IUriOpener>().OpenUri(DiscordServerInviteUrl);
        };

        RefreshData();
        _discordAuthManager.DataUpdated += RefreshData;
    }

    private void RefreshData()
    {
        UrlEdit.TextRope = new Rope.Leaf(
            _discordAuthManager.AuthUrl != string.Empty
                ? _discordAuthManager.AuthUrl
                : "Проверка...");
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            _discordAuthManager.DataUpdated -= RefreshData;
        }
    }
}
