using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._BlackM.PhraseWheel;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.PhraseWheel;

[GenerateTypedNameReferences]
public sealed partial class PhraseWheelWindow : FancyWindow
{
    public event Action<PhraseWheelEntryPrototype, string?>? OnPhraseSelected;

    private string? _customColor;

    public PhraseWheelWindow(IEnumerable<PhraseWheelEntryPrototype> phrases, IResourceCache resCache)
    {
        RobustXamlLoader.Load(this);

        var colorPanel = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            Margin = new Thickness(4, 0, 4, 4),
        };

        var colorLabel = new Label
        {
            Text = "Цвет текста:",
            VerticalAlignment = VAlignment.Center,
        };

        var hexInput = new LineEdit
        {
            MinSize = new Vector2(180, 0),
            VerticalAlignment = VAlignment.Center,
        };

        var hintLabel = new Label
        {
            Text = "(#RRGGBB)",
            VerticalAlignment = VAlignment.Center,
            FontColorOverride = new Color(0.6f, 0.6f, 0.6f),
        };

        var previewStyle = new StyleBoxFlat { BackgroundColor = Color.Transparent };
        var colorPreview = new PanelContainer
        {
            MinSize = new Vector2(24, 24),
            VerticalAlignment = VAlignment.Center,
            PanelOverride = previewStyle,
        };

        var resetBtn = new Button
        {
            Text = "✕",
            ToolTip = "Сбросить цвет",
            MinSize = new Vector2(28, 0),
        };

        hexInput.OnTextChanged += args =>
        {
            var raw = args.Text.Trim();
            if (string.IsNullOrEmpty(raw))
            {
                _customColor = null;
                previewStyle.BackgroundColor = Color.Transparent;
                colorPreview.PanelOverride = previewStyle;
                return;
            }

            if (!raw.StartsWith('#'))
                raw = "#" + raw;

            try
            {
                var parsed = Color.FromHex(raw);
                _customColor = raw;
                previewStyle.BackgroundColor = parsed;
            }
            catch
            {
                _customColor = null;
                previewStyle.BackgroundColor = new Color(0.5f, 0f, 0f);
            }
            colorPreview.PanelOverride = previewStyle;
        };

        resetBtn.OnPressed += _ =>
        {
            hexInput.Text = string.Empty;
            _customColor = null;
            previewStyle.BackgroundColor = Color.Transparent;
            colorPreview.PanelOverride = previewStyle;
        };

        colorPanel.AddChild(colorLabel);
        colorPanel.AddChild(hexInput);
        colorPanel.AddChild(hintLabel);
        colorPanel.AddChild(colorPreview);
        colorPanel.AddChild(resetBtn);

        if (CategoryTabs.Parent is BoxContainer tabsParent)
        {
            tabsParent.AddChild(colorPanel);
            var idx = 0;
            foreach (var child in tabsParent.Children)
            {
                if (child == CategoryTabs) break;
                idx++;
            }
            colorPanel.SetPositionInParent(idx);
        }

        var grouped = phrases
            .GroupBy(p => p.Category)
            .OrderBy(g => g.Key)
            .ToList();

        foreach (var group in grouped)
        {
            var scroll = new ScrollContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
            };

            var grid = new GridContainer
            {
                Columns = 4,
                HSeparationOverride = 4,
                VSeparationOverride = 4,
                Margin = new Thickness(4),
            };

            foreach (var phrase in group)
            {
                var btn = new PhraseWheelButton(phrase, resCache);
                btn.OnPressed += () => OnPhraseSelected?.Invoke(phrase, _customColor);
                grid.AddChild(btn);
            }

            scroll.AddChild(grid);
            CategoryTabs.AddChild(scroll);
            CategoryTabs.SetTabTitle(CategoryTabs.ChildCount - 1, group.Key);
        }
    }
}

public sealed class PhraseWheelButton : Button
{
    public new event Action? OnPressed;

    public PhraseWheelButton(PhraseWheelEntryPrototype phrase, IResourceCache resCache)
    {
        MinSize = new Vector2(100, 90);
        MaxSize = new Vector2(120, 100);
        ToolTip = phrase.Text;

        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 2,
            Margin = new Thickness(4),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };

        var icon = new TextureRect
        {
            MinSize = new Vector2(48, 48),
            MaxSize = new Vector2(48, 48),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            HorizontalAlignment = HAlignment.Center,
        };

        try
        {
            var texture = phrase.Icon switch
            {
                SpriteSpecifier.Texture tex => resCache.GetResource<TextureResource>(tex.TexturePath).Texture,
                SpriteSpecifier.Rsi rsi => resCache.GetResource<RSIResource>(rsi.RsiPath).RSI[rsi.RsiState].Frame0,
                _ => null,
            };
            if (texture != null)
                icon.Texture = texture;
        }
        catch { }

        var displayText = string.IsNullOrEmpty(phrase.Label) ? phrase.Text : phrase.Label;
        if (displayText.Length > 14)
            displayText = displayText[..12] + "..";

        var label = new Label
        {
            Text = displayText,
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = Color.White,
        };

        vbox.AddChild(icon);
        vbox.AddChild(label);
        AddChild(vbox);

        OnButtonUp += _ => OnPressed?.Invoke();
    }
}