using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._BlackM.PhraseWheel;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Systems.PhraseWheel;

[GenerateTypedNameReferences]
public sealed partial class PhraseWheelWindow : FancyWindow
{
    public event Action<PhraseWheelEntryPrototype, string?>? OnPhraseSelected;
    public event Action<string?>? OnColorChanged;

    private string? _customColor;
    public string? CurrentColor => _customColor;

    private IResourceCache _resCache = null!;
    private ScrollContainer _recentScroll = null!;
    private GridContainer _recentGrid = null!;

    public PhraseWheelWindow(IEnumerable<PhraseWheelEntryPrototype> phrases, IResourceCache resCache,
        string? initialColor = null, IEnumerable<PhraseWheelEntryPrototype>? recentPhrases = null)
    {
        RobustXamlLoader.Load(this);
        _customColor = initialColor;
        _resCache = resCache;

        try
        {
            var bgTexture = resCache.GetResource<TextureResource>(
                "/Textures/_BlackM/Interface/PhraseWheel/phrasewheel_bg.png").Texture;

            BackgroundPanel.PanelOverride = new StyleBoxTexture
            {
                Texture = bgTexture,
                PatchMarginLeft = 10,
                PatchMarginRight = 10,
                PatchMarginTop = 10,
                PatchMarginBottom = 10,
                ContentMarginLeftOverride = 4,
                ContentMarginTopOverride = 4,
            };
        }
        catch
        {
        }

        var colorPanel = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            Margin = new Thickness(4, 0, 4, 4),
        };

        var colorLabel = new Label
        {
            Text = "Text Color:",
            VerticalAlignment = VAlignment.Center,
        };

        var hexInput = new LineEdit
        {
            MinSize = new Vector2(180, 0),
            VerticalAlignment = VAlignment.Center,
            Text = initialColor ?? string.Empty,
        };

        var hintLabel = new Label
        {
            Text = "(#RRGGBB)",
            VerticalAlignment = VAlignment.Center,
            FontColorOverride = new Color(0.6f, 0.6f, 0.6f),
        };

        var previewStyle = new StyleBoxFlat { BackgroundColor = Color.Transparent };
        var colorPreview = new PanelContainer
        {
            MinSize = new Vector2(24, 24),
            VerticalAlignment = VAlignment.Center,
            PanelOverride = previewStyle,
        };

        var resetBtn = new Button
        {
            Text = "✕",
            ToolTip = "Reset Color",
            MinSize = new Vector2(28, 0),
        };

        hexInput.OnTextChanged += args =>
        {
            var raw = args.Text.Trim();
            if (string.IsNullOrEmpty(raw))
            {
                _customColor = null;
                previewStyle.BackgroundColor = Color.Transparent;
                colorPreview.PanelOverride = previewStyle;
                OnColorChanged?.Invoke(_customColor);
                return;
            }

            if (!raw.StartsWith('#'))
                raw = "#" + raw;

            try
            {
                var parsed = Color.FromHex(raw);
                _customColor = raw;
                previewStyle.BackgroundColor = parsed;
            }
            catch
            {
                _customColor = null;
                previewStyle.BackgroundColor = new Color(0.5f, 0f, 0f);
            }
            colorPreview.PanelOverride = previewStyle;
            OnColorChanged?.Invoke(_customColor);
        };

        resetBtn.OnPressed += _ =>
        {
            hexInput.Text = string.Empty;
            _customColor = null;
            previewStyle.BackgroundColor = Color.Transparent;
            colorPreview.PanelOverride = previewStyle;
            OnColorChanged?.Invoke(_customColor);
        };

        if (!string.IsNullOrEmpty(initialColor))
        {
            try
            {
                previewStyle.BackgroundColor = Color.FromHex(initialColor);
                colorPreview.PanelOverride = previewStyle;
            }
            catch { /* ignore invalid color */ }
        }

        colorPanel.AddChild(colorLabel);
        colorPanel.AddChild(hexInput);
        colorPanel.AddChild(hintLabel);
        colorPanel.AddChild(colorPreview);
        colorPanel.AddChild(resetBtn);

        if (CategoryTabs.Parent is BoxContainer tabsParent)
        {
            tabsParent.AddChild(colorPanel);
            var idx = 0;
            foreach (var child in tabsParent.Children)
            {
                if (child == CategoryTabs) break;
                idx++;
            }
            colorPanel.SetPositionInParent(idx);
        }

        _recentGrid = new GridContainer
        {
            Columns = 3,
            HSeparationOverride = 4,
            VSeparationOverride = 4,
            Margin = new Thickness(4),
        };

        _recentScroll = new ScrollContainer
        {
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        _recentScroll.AddChild(_recentGrid);
        CategoryTabs.AddChild(_recentScroll);
        CategoryTabs.SetTabTitle(0, "Недавние");
        UpdateRecentTab(recentPhrases ?? Enumerable.Empty<PhraseWheelEntryPrototype>());

        var grouped = phrases
            .GroupBy(p => p.Category)
            .OrderBy(g => g.Key)
            .ToList();

        var allButtons = new List<PhraseWheelButton>();

        foreach (var group in grouped)
        {
            var scroll = new ScrollContainer
            {
                HorizontalExpand = true,
                VerticalExpand = true,
            };

            var grid = new GridContainer
            {
                Columns = 3,
                HSeparationOverride = 4,
                VSeparationOverride = 4,
                Margin = new Thickness(4),
            };

            var sortedPhrases = group
                .OrderBy(p => p.Order)
                .ToList();

            foreach (var phrase in sortedPhrases)
            {
                var btn = new PhraseWheelButton(phrase, resCache);
                btn.OnPressed += () => OnPhraseSelected?.Invoke(phrase, _customColor);
                grid.AddChild(btn);
                allButtons.Add(btn);
            }

            scroll.AddChild(grid);
            CategoryTabs.AddChild(scroll);
            CategoryTabs.SetTabTitle(CategoryTabs.ChildCount - 1, group.Key);
        }

        _categoryButtons = allButtons;
        _phraseButtons = new List<PhraseWheelButton>(_categoryButtons);
        _phraseButtons.AddRange(_recentButtons);
    }

    private List<PhraseWheelButton> _categoryButtons = new();
    private List<PhraseWheelButton> _recentButtons = new();
    private List<PhraseWheelButton> _phraseButtons = new();

    public void UpdateRecentTab(IEnumerable<PhraseWheelEntryPrototype> recentPhrases)
    {
        _recentGrid.RemoveAllChildren();
        _recentButtons = new List<PhraseWheelButton>();

        foreach (var phrase in recentPhrases)
        {
            var btn = new PhraseWheelButton(phrase, _resCache);
            btn.OnPressed += () => OnPhraseSelected?.Invoke(phrase, _customColor);
            _recentGrid.AddChild(btn);
            _recentButtons.Add(btn);
        }

        _phraseButtons = new List<PhraseWheelButton>(_categoryButtons);
        _phraseButtons.AddRange(_recentButtons);
    }

    public void SetPhraseButtonsEnabled(bool enabled)
    {
        foreach (var btn in _phraseButtons)
        {
            btn.Disabled = !enabled;
            btn.RefreshDisabledVisual();
        }
    }
}

public sealed class PhraseWheelButton : ContainerButton
{
    public new event Action? OnPressed;

    private readonly PanelContainer _background;
    private readonly StyleBoxTexture _normalStyle;
    private readonly StyleBoxTexture _hoverStyle;
    private readonly StyleBoxTexture _pressedStyle;
    private readonly StyleBoxTexture _disabledStyle;

    public PhraseWheelButton(PhraseWheelEntryPrototype phrase, IResourceCache resCache)
    {
        MinSize = new Vector2(128, 108);
        MaxSize = new Vector2(128, 108);
        ToolTip = phrase.Text;

        _normalStyle = MakeButtonStyle(resCache, "/Textures/_BlackM/Interface/PhraseWheel/phrasewheel_button_normal.png");
        _hoverStyle = MakeButtonStyle(resCache, "/Textures/_BlackM/Interface/PhraseWheel/phrasewheel_button_hover.png");
        _pressedStyle = MakeButtonStyle(resCache, "/Textures/_BlackM/Interface/PhraseWheel/phrasewheel_button_pressed.png");
        _disabledStyle = MakeButtonStyle(resCache, "/Textures/_BlackM/Interface/PhraseWheel/phrasewheel_button_disabled.png");

        _background = new PanelContainer
        {
            PanelOverride = _normalStyle,
            HorizontalExpand = true,
            VerticalExpand = true,
        };
        AddChild(_background);

        var vbox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            Margin = new Thickness(4),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
        };

        var icon = new TextureRect
        {
            MinSize = new Vector2(36, 36),
            MaxSize = new Vector2(36, 36),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            HorizontalAlignment = HAlignment.Center,
        };

        try
        {
            var texture = phrase.Icon switch
            {
                SpriteSpecifier.Texture tex => resCache.GetResource<TextureResource>(tex.TexturePath).Texture,
                SpriteSpecifier.Rsi rsi => resCache.GetResource<RSIResource>(rsi.RsiPath).RSI[rsi.RsiState].Frame0,
                _ => null,
            };
            if (texture != null)
                icon.Texture = texture;
        }
        catch { }

        var displayText = string.IsNullOrEmpty(phrase.Label) ? phrase.Text : phrase.Label;

        var labelHolder = new PanelContainer
        {
            MinSize = new Vector2(120, 40),
            MaxSize = new Vector2(120, 40),
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            RectClipContent = true,
        };

        var label = new RichTextLabel
        {
            HorizontalAlignment = HAlignment.Center,
            VerticalAlignment = VAlignment.Center,
            MaxWidth = 120,
        };
        label.SetMessage(displayText);
        labelHolder.AddChild(label);

        vbox.AddChild(icon);
        vbox.AddChild(labelHolder);
        _background.AddChild(vbox);

        OnButtonDown += _ => _background.PanelOverride = _pressedStyle;
        OnButtonUp += _ =>
        {
            _background.PanelOverride = Disabled ? _disabledStyle : _hoverStyle;
            OnPressed?.Invoke();
        };
        OnMouseEntered += _ => { if (!Disabled) _background.PanelOverride = _hoverStyle; };
        OnMouseExited += _ => { if (!Disabled) _background.PanelOverride = _normalStyle; };

        RefreshDisabledVisual();
    }

    public void RefreshDisabledVisual()
    {
        _background.PanelOverride = Disabled ? _disabledStyle : _normalStyle;
    }

    private static StyleBoxTexture MakeButtonStyle(IResourceCache resCache, string path)
    {
        var tex = resCache.GetResource<TextureResource>(path).Texture;
        return new StyleBoxTexture
        {
            Texture = tex,
            PatchMarginLeft = 8,
            PatchMarginRight = 8,
            PatchMarginTop = 8,
            PatchMarginBottom = 8,
            ContentMarginLeftOverride = 4,
            ContentMarginTopOverride = 4,
        };
    }
}
