using Content.Shared._BlackM.Passport;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._BlackM.Passport.UI;

[GenerateTypedNameReferences]
public sealed partial class PassportWindow : DefaultWindow
{
    private static readonly Color ErrorColor  = Color.FromHex("#C0392B");
    private static readonly Color NormalColor = Color.FromHex("#14100A");

    public PassportWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(PassportBoundUserInterfaceState state, IEntityManager entMan)
    {
        SurnameLabel.Text        = state.Surname;
        NameLabel.Text           = state.OwnerName;
        JobLabel.Text            = state.JobTitle;
        CityLabel.Text           = state.City;
        PassportNumberLabel.Text = state.PassportNumber;
        IssuedDateLabel.Text     = state.IssuedDate;
        SignatureLabel.Text      = state.Signature;
        MrzLine1Label.Text       = state.MrzLine1;
        MrzLine2Label.Text       = state.MrzLine2;

        ResetColors();

        if (state.HasBureaucraticError && !string.IsNullOrEmpty(state.ErrorField))
            HighlightError(state.ErrorField);

        if (state.OwnerEntity is { } netEnt && entMan.TryGetEntity(netEnt, out var uid))
            OwnerSpriteView.SetEntity(uid);
        else
            OwnerSpriteView.SetEntity(null);
    }

    private void ResetColors()
    {
        SurnameLabel.FontColorOverride        = NormalColor;
        NameLabel.FontColorOverride           = NormalColor;
        JobLabel.FontColorOverride            = NormalColor;
        CityLabel.FontColorOverride           = NormalColor;
        PassportNumberLabel.FontColorOverride = NormalColor;
        IssuedDateLabel.FontColorOverride     = NormalColor;
    }

    private void HighlightError(string field)
    {
        switch (field)
        {
            case "city":           CityLabel.FontColorOverride           = ErrorColor; break;
            case "passportnumber": PassportNumberLabel.FontColorOverride = ErrorColor; break;
            case "surname":        SurnameLabel.FontColorOverride        = ErrorColor; break;
            case "name":           NameLabel.FontColorOverride           = ErrorColor; break;
            case "job":            JobLabel.FontColorOverride            = ErrorColor; break;
            case "issueddate":     IssuedDateLabel.FontColorOverride     = ErrorColor; break;
        }
    }
}