using System.Numerics;
using Content.Shared._BlackM.Passport;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._BlackM.Passport.UI;

[GenerateTypedNameReferences]
public sealed partial class PassportWindow : PassportFramelessWindow
{
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private const float PortraitViewSize = 300f;
    private const float PortraitOffsetX  = -64f;
    private const float PortraitOffsetY  = 0f;

    private const string FontMain   = "/Fonts/_BlackM/Passport/PT_Serif-Web-Regular.ttf";
    private const string FontItalic = "/Fonts/_BlackM/Passport/MarckScript-Regular.ttf";
    private const string FontMono   = "/Fonts/NotoSansMono/NotoSansMono-Regular.ttf";

    private static readonly Color Ink      = Color.FromHex("#2A2820");
    private static readonly Color Caption  = Color.FromHex("#7A7456");
    private static readonly Color Foil     = Color.FromHex("#D2C48F");
    private static readonly Color Approved = Color.FromHex("#3E7A3E");
    private static readonly Color Denied   = Color.FromHex("#9A3A2E");
    private static readonly Color Pending  = Color.FromHex("#8A8466");
    private static readonly Color HintHover = Color.FromHex("#2F5A35");

    private const float FlipTime = 0.16f;

    private readonly Control[] _pages;
    private int _page;
    private float _flip = 1f;

    public event Action<int, int>? OnPageTurned;

    public PassportWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _pages = new Control[] { PageCover, PageIdentity, PageService };

        LayoutContainer.SetMarginLeft(OwnerSpriteView, PortraitOffsetX);
        LayoutContainer.SetMarginTop(OwnerSpriteView, PortraitOffsetY);
        LayoutContainer.SetMarginRight(OwnerSpriteView, PortraitOffsetX + PortraitViewSize);
        LayoutContainer.SetMarginBottom(OwnerSpriteView, PortraitOffsetY + PortraitViewSize);

        SetupFonts();

        Click(CoverZone,        () => SetPage(1));
        Click(IdentityNextZone, () => SetPage(2));
        Click(IdentityPrevZone, () => SetPage(0));
        Click(ServicePrevZone,  () => SetPage(1));

        Click(CoverClose,    Close);
        Click(IdentityClose, Close);
        Click(ServiceClose,  Close);

        SetPage(0, animate: false);
    }

    private void SetupFonts()
    {
        foreach (var l in new[] { SurnameLabel, NameLabel, CityLabel, JobLabel, AdditionalJobLabel,
                                  PassportNumberLabel, IssuedDateLabel, OrgLabel })
            l.FontColorOverride = Ink;

        SetFitted(OrgLabel, "Black Mesa Research Facility", WideWidth);

        foreach (var l in new[] { SurnameCaption, NameCaption, CityCaption, NumberCaption, IssuedCaption,
                                  JobCaption, AdditionalJobCaption, OrgCaption })
            l.FontColorOverride = Caption;

        Apply(SignatureLabel, LoadFont(FontItalic, 25));
        SignatureLabel.FontColorOverride = Color.FromHex("#1F2A55");

        var mono = LoadFont(FontMono, 12);
        foreach (var l in new[] { MrzLine1Label, MrzLine2Label })
        {
            Apply(l, mono);
            l.FontColorOverride = Color.FromHex("#3A382C");
        }

        Apply(StatusLabel, LoadFont(FontMain, 14));
        Apply(CoverHint, LoadFont(FontMain, 12));
        CoverHint.FontColorOverride = Foil.WithAlpha(0.75f);

        foreach (var h in new[] { IdentityPrevHint, IdentityNextHint, ServicePrevHint })
            h.FontColorOverride = Caption;
    }

    private const float CharWidthFactor = 0.62f;
    private const int   MaxValueSize    = 17;
    private const int   MinValueSize    = 10;
    private const float NarrowWidth     = 252f;
    private const float WideWidth       = 260f;

    private readonly Dictionary<int, Font?> _mainFonts = new();

    private void SetFitted(Label label, string? text, float maxWidth)
    {
        text ??= string.Empty;
        label.Text = text;

        var size = (int) MathF.Floor(maxWidth / (Math.Max(1, text.Length) * CharWidthFactor));
        size = Math.Clamp(size, MinValueSize, MaxValueSize);

        if (!_mainFonts.TryGetValue(size, out var font))
            _mainFonts[size] = font = LoadFont(FontMain, size);

        Apply(label, font);
    }

    private Font? LoadFont(string path, int size)
        => _resourceCache.TryGetResource<FontResource>(path, out var res) ? new VectorFont(res, size) : null;

    private static void Apply(Label label, Font? font)
    {
        if (font != null)
            label.FontOverride = font;
    }

    private static void Click(Control control, Action action)
    {
        control.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            action();
            args.Handle();
        };
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
        => relativeMousePos.Y < 46f ? DragMode.Move : DragMode.None;

    private void SetPage(int page, bool animate = true)
    {
        var old = _page;
        _page = Math.Clamp(page, 0, _pages.Length - 1);

        for (var i = 0; i < _pages.Length; i++)
        {
            _pages[i].Visible = i == _page;
            _pages[i].Modulate = Color.White;
        }

        IdentityNextHint.Visible = _page == 1;

        if (!animate || old == _page)
        {
            _flip = 1f;
            return;
        }

        _flip = 0f;
        _pages[_page].Modulate = Color.White.WithAlpha(0f);
        OnPageTurned?.Invoke(old, _page);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_flip >= 1f)
            return;

        _flip = MathF.Min(1f, _flip + args.DeltaSeconds / FlipTime);
        var eased = 1f - (1f - _flip) * (1f - _flip);
        _pages[_page].Modulate = Color.White.WithAlpha(eased);
    }

    public void UpdateState(PassportBoundUserInterfaceState state, IEntityManager entMan)
    {
        SetFitted(SurnameLabel, state.Surname, NarrowWidth);
        SetFitted(NameLabel, state.OwnerName, NarrowWidth);
        SetFitted(CityLabel, state.City, NarrowWidth);
        SetFitted(PassportNumberLabel, state.PassportNumber, NarrowWidth);
        SetFitted(IssuedDateLabel, state.IssuedDate, NarrowWidth);

        SetFitted(JobLabel, state.JobTitle, WideWidth);
        SetFitted(AdditionalJobLabel,
            string.IsNullOrWhiteSpace(state.AdditionalJob) ? "—" : state.AdditionalJob, WideWidth);

        SignatureLabel.Text = state.Signature;
        MrzLine1Label.Text       = state.MrzLine1;
        MrzLine2Label.Text       = state.MrzLine2;

        var approved = state.Stamp == PassportStampState.Approved;
        var denied   = state.Stamp == PassportStampState.Denied;

        StampApprovedTexture.Visible = approved;
        StampDeniedTexture.Visible   = denied;

        StatusLabel.Text = approved ? "Проверено" : denied ? "Отклонено" : "Ожидает проверки";
        StatusLabel.FontColorOverride = approved ? Approved : denied ? Denied : Pending;

        if (state.OwnerEntity is { } netEnt && entMan.TryGetEntity(netEnt, out var uid))
            OwnerSpriteView.SetEntity(uid);
        else
            OwnerSpriteView.SetEntity(null);
    }
}
