using Content.Shared._BlackM.Passport;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._BlackM.Passport.UI;

[GenerateTypedNameReferences]
public sealed partial class PassportWindow : DefaultWindow
{
    public PassportWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(PassportBoundUserInterfaceState state, IEntityManager entMan)
    {
        SurnameLabel.Text        = state.Surname;
        NameLabel.Text           = state.OwnerName;
        JobLabel.Text            = state.JobTitle;
        CityLabel.Text           = state.City;
        PassportNumberLabel.Text = state.PassportNumber;
        IssuedDateLabel.Text     = state.IssuedDate;
        SignatureLabel.Text      = state.Signature;
        MrzLine1Label.Text       = state.MrzLine1;
        MrzLine2Label.Text       = state.MrzLine2;

        if (state.OwnerEntity is { } netEnt && entMan.TryGetEntity(netEnt, out var uid))
            OwnerSpriteView.SetEntity(uid);
        else
            OwnerSpriteView.SetEntity(null);
    }
}
