using Content.Shared._BlackM.Passport;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._BlackM.Passport.UI;

[GenerateTypedNameReferences]
public sealed partial class PassportCheckerWindow : DefaultWindow
{
    private static readonly Color NormalBg   = Color.FromHex("#3A3A3A");
    private static readonly Color SelectedBg = Color.FromHex("#F1C40F");
    private static readonly Color ErrorBg    = Color.FromHex("#C0392B");

    private static readonly Color NormalText   = Color.White;
    private static readonly Color SelectedText = Color.Black;
    private static readonly Color ErrorText    = Color.White;

    private static readonly Color GoodVerdict = Color.FromHex("#4CAF50");
    private static readonly Color BadVerdict  = Color.FromHex("#E74C3C");

    private static readonly Color AccuseBg = Color.FromHex("#8B2E2E");
    private static readonly Color CleanBg  = Color.FromHex("#2E6B3E");
    private static readonly Color EjectBg  = Color.FromHex("#3A3A3A");

    public event Action<string>? OnFieldSelected;
    public event Action? OnAccusePressed;
    public event Action? OnCleanPressed;
    public event Action? OnEjectPressed;

    private readonly Dictionary<string, Button> _fieldButtons;

    private static StyleBoxFlat MakeBox(Color color) => new()
    {
        BackgroundColor = color,
        ContentMarginLeftOverride = 6,
        ContentMarginRightOverride = 6,
        ContentMarginTopOverride = 2,
        ContentMarginBottomOverride = 2,
    };

    public PassportCheckerWindow()
    {
        RobustXamlLoader.Load(this);

        _fieldButtons = new Dictionary<string, Button>
        {
            ["surname"]        = DocSurnameButton,
            ["name"]           = DocNameButton,
            ["city"]           = DocCityButton,
            ["job"]            = DocJobButton,
            ["passportnumber"] = DocNumberButton,
            ["issueddate"]     = DocDateButton,
        };

        foreach (var (field, button) in _fieldButtons)
        {
            button.OnPressed += _ => OnFieldSelected?.Invoke(field);
            button.StyleBoxOverride = MakeBox(NormalBg);
            button.Label.FontColorOverride = NormalText;
        }

        AccuseButton.OnPressed += _ => OnAccusePressed?.Invoke();
        CleanButton.OnPressed  += _ => OnCleanPressed?.Invoke();
        EjectButton.OnPressed  += _ => OnEjectPressed?.Invoke();

        AccuseButton.StyleBoxOverride = MakeBox(AccuseBg);
        AccuseButton.Label.FontColorOverride = Color.White;
        CleanButton.StyleBoxOverride = MakeBox(CleanBg);
        CleanButton.Label.FontColorOverride = Color.White;
        EjectButton.StyleBoxOverride = MakeBox(EjectBg);
        EjectButton.Label.FontColorOverride = Color.White;
    }

    public void UpdateState(PassportCheckerBoundUserInterfaceState state)
    {
        RefSurnameLabel.Text = state.RefSurname ?? "";
        RefNameLabel.Text    = state.RefOwnerName ?? "";
        RefCityLabel.Text    = state.RefCity ?? "";
        RefJobLabel.Text     = state.RefJobTitle ?? "";
        RefNumberLabel.Text  = state.RefPassportNumber ?? "";
        RefDateLabel.Text    = state.RefIssuedDate ?? "";

        DocSurnameButton.Text = state.DocSurname ?? "";
        DocNameButton.Text    = state.DocOwnerName ?? "";
        DocCityButton.Text    = state.DocCity ?? "";
        DocJobButton.Text     = state.DocJobTitle ?? "";
        DocNumberButton.Text  = state.DocPassportNumber ?? "";
        DocDateButton.Text    = state.DocIssuedDate ?? "";

        var interactable = state.HasPassport && state.Result == PassportCheckerResult.None;
        foreach (var button in _fieldButtons.Values)
            button.Disabled = !interactable;

        AccuseButton.Disabled = !interactable;
        CleanButton.Disabled  = !interactable;
        EjectButton.Disabled  = !state.HasPassport;

        foreach (var button in _fieldButtons.Values)
        {
            button.StyleBoxOverride = MakeBox(NormalBg);
            button.Label.FontColorOverride = NormalText;
        }

        if (state.SelectedField != null
            && state.Result == PassportCheckerResult.None
            && _fieldButtons.TryGetValue(state.SelectedField, out var selectedBtn))
        {
            selectedBtn.StyleBoxOverride = MakeBox(SelectedBg);
            selectedBtn.Label.FontColorOverride = SelectedText;
        }

        if (state.ConfirmedErrorField != null
            && _fieldButtons.TryGetValue(state.ConfirmedErrorField, out var errorBtn))
        {
            errorBtn.StyleBoxOverride = MakeBox(ErrorBg);
            errorBtn.Label.FontColorOverride = ErrorText;
        }

        VerdictLabel.Text = state.Result switch
        {
            PassportCheckerResult.CorrectCatch    => Loc.GetString("passport-checker-verdict-correct-catch"),
            PassportCheckerResult.WrongAccusation => Loc.GetString("passport-checker-verdict-wrong-accusation"),
            PassportCheckerResult.CorrectClean    => Loc.GetString("passport-checker-verdict-correct-clean"),
            PassportCheckerResult.Missed          => Loc.GetString("passport-checker-verdict-missed"),
            _ => ""
        };

        VerdictLabel.FontColorOverride = state.Result switch
        {
            PassportCheckerResult.CorrectCatch    => GoodVerdict,
            PassportCheckerResult.CorrectClean    => GoodVerdict,
            PassportCheckerResult.Missed          => GoodVerdict,
            PassportCheckerResult.WrongAccusation => BadVerdict,
            _ => null
        };
    }
}
