using System;
using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._BlackM.Ghost.Customization;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client._BlackM.Ghost.Customization;

[GenerateTypedNameReferences]
public sealed partial class GhostCustomizationWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;

    private static readonly Color AccentTeal = Color.FromHex("#4FD1C5");

    private SpriteSystem _sprite = default!;
    private string? _selectedId;

    private GhostCustomizationBoundUserInterfaceState? _lastState;

    public event Action<string>? OnSpriteChosen;

    public GhostCustomizationWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entManager.System<SpriteSystem>();

        CloseButton.OnPressed += _ => Close();

        HeaderDivider.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = Color.White.WithAlpha(0.12f),
            BorderColor = Color.White.WithAlpha(0.18f),
            BorderThickness = new Thickness(0, 0, 0, 1),
            ContentMarginLeftOverride = 0,
            ContentMarginRightOverride = 0,
            ContentMarginTopOverride = 0,
            ContentMarginBottomOverride = 0
        };

        ListHeader.Modulate = Color.White;
    }

    public void UpdateState(GhostCustomizationBoundUserInterfaceState state)
    {
        if (_lastState != null && StatesEqual(_lastState, state))
            return;

        _lastState = state;

        var previousScroll = SpriteScroll.GetScrollValue();

        SpriteList.RemoveAllChildren();
        _selectedId = state.Selected;
        foreach (var option in state.Available)
        {
            if (!_proto.TryIndex<GhostSpritePrototype>(option.Id, out var proto))
                continue;

            var id = proto.ID;
            var texture = _sprite.GetFrame(proto.Sprite, TimeSpan.Zero);
            var isSelected = id == state.Selected;
            var isLocked = option.Locked;
            var displayName = string.IsNullOrEmpty(proto.Name) ? id : proto.Name;

            var row = new ContainerButton
            {
                MinSize = new Vector2(0, 52),
                HorizontalExpand = true,
                ToolTip = isLocked
                    ? Loc.GetString("ghost-customization-row-tooltip", ("name", displayName), ("reason", option.LockReason ?? Loc.GetString("ghost-customization-status-whitelist")))
                    : displayName,
                Disabled = isLocked
            };

            var panel = new PanelContainer
            {
                PanelOverride = MakeRowStyleBox(isSelected, disabled: isLocked),
                MouseFilter = Control.MouseFilterMode.Ignore
            };

            var layout = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(8, 4, 8, 4),
                SeparationOverride = 10,
                MouseFilter = Control.MouseFilterMode.Ignore
            };

            var icon = new TextureRect
            {
                Texture = texture,
                MinSize = new Vector2(32, 32),
                MaxSize = new Vector2(32, 32),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                MouseFilter = Control.MouseFilterMode.Ignore
            };

            var info = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
                MouseFilter = Control.MouseFilterMode.Ignore
            };

            var label = new Label
            {
                Text = displayName,
                VerticalAlignment = VAlignment.Center,
                HorizontalExpand = true,
                ClipText = true,
                MouseFilter = Control.MouseFilterMode.Ignore,
                Modulate = Color.White
            };

            var meta = new Label
            {
                Text = isLocked
                    ? (option.LockReason ?? Loc.GetString("ghost-customization-status-whitelist"))
                    : Loc.GetString("ghost-customization-status-available"),
                StyleClasses = { "WindowFooterText" },
                VerticalAlignment = VAlignment.Center,
                MouseFilter = Control.MouseFilterMode.Ignore,
                Modulate = isLocked ? Color.FromHex("#FFB3A8") : Color.White
            };

            info.AddChild(label);
            info.AddChild(meta);

            var status = new Label
            {
                Text = isLocked ? "🔒" : string.Empty,
                MinSize = new Vector2(20, 20),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                MouseFilter = Control.MouseFilterMode.Ignore,
                Modulate = Color.White
            };

            layout.AddChild(icon);
            layout.AddChild(info);
            layout.AddChild(status);
            panel.AddChild(layout);
            row.AddChild(panel);

            row.OnPressed += _ =>
            {
                if (isLocked)
                    return;

                OnSpriteChosen?.Invoke(id);
                _selectedId = id;

                foreach (var child in SpriteList.Children)
                {
                    if (child is not ContainerButton rowButton || rowButton.Children.FirstOrDefault() is not PanelContainer rowPanel)
                        continue;

                    rowPanel.PanelOverride = MakeRowStyleBox(ReferenceEquals(rowButton, row), disabled: false);
                }
            };

            row.OnMouseEntered += _ =>
            {
                if (_selectedId != id && !isLocked)
                    panel.PanelOverride = MakeRowStyleBox(false, hovered: true);
            };

            row.OnMouseExited += _ =>
            {
                if (_selectedId != id && !isLocked)
                    panel.PanelOverride = MakeRowStyleBox(false);
            };

            SpriteList.AddChild(row);
        }

        SpriteList.InvalidateMeasure();
        SpriteScroll.InvalidateMeasure();
        SpriteScroll.SetScrollValue(previousScroll);
    }

    private static bool StatesEqual(GhostCustomizationBoundUserInterfaceState a, GhostCustomizationBoundUserInterfaceState b)
    {
        if (a.Selected != b.Selected)
            return false;

        if (a.Available.Count != b.Available.Count)
            return false;

        for (var i = 0; i < a.Available.Count; i++)
        {
            var x = a.Available[i];
            var y = b.Available[i];
            if (x.Id != y.Id || x.Locked != y.Locked || x.LockReason != y.LockReason)
                return false;
        }

        return true;
    }

    private static StyleBoxFlat MakeRowStyleBox(bool selected, bool hovered = false, bool disabled = false)
    {
        if (selected)
        {
            return new StyleBoxFlat
            {
                BackgroundColor = AccentTeal.WithAlpha(0.32f),
                BorderColor = AccentTeal,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4
            };
        }

        if (disabled)
        {
            return new StyleBoxFlat
            {
                BackgroundColor = Color.Black.WithAlpha(0.20f),
                BorderColor = Color.White.WithAlpha(0.25f),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4
            };
        }

        if (hovered)
        {
            return new StyleBoxFlat
            {
                BackgroundColor = Color.White.WithAlpha(0.10f),
                BorderColor = Color.White.WithAlpha(0.6f),
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 4,
                ContentMarginRightOverride = 4,
                ContentMarginTopOverride = 4,
                ContentMarginBottomOverride = 4
            };
        }

        return new StyleBoxFlat
        {
            BackgroundColor = Color.Black.WithAlpha(0.28f),
            BorderColor = Color.White.WithAlpha(0.6f),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4
        };
    }
}
