using System;
using System.Linq;
using System.Numerics;
using Content.Shared._BlackM.Ghost.Customization;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client._BlackM.Ghost.Customization;

[GenerateTypedNameReferences]
public sealed partial class GhostCustomizationWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;

    private static readonly Color SelectedBorderColor = Color.FromHex("#63de5d");
    private static readonly Color HoverBorderColor = Color.FromHex("#8a8a8a");
    private static readonly Color DefaultBorderColor = Color.FromHex("#3a3a3a");

    private SpriteSystem _sprite = default!;

    public event Action<string>? OnSpriteChosen;

    public GhostCustomizationWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entManager.System<SpriteSystem>();
    }

    public void UpdateState(GhostCustomizationBoundUserInterfaceState state)
    {
        SpriteGrid.RemoveAllChildren();

        var sorted = state.Available
            .Select(id => _proto.TryIndex<GhostSpritePrototype>(id, out var p) ? p : null)
            .Where(p => p != null)
            .OrderBy(p => p!.Name)
            .ThenBy(p => p!.ID);

        foreach (var proto in sorted)
        {
            var id = proto!.ID;
            var texture = _sprite.GetFrame(proto.Sprite, TimeSpan.Zero);
            var isSelected = id == state.Selected;
            var displayName = string.IsNullOrEmpty(proto.Name) ? id : proto.Name;

            var card = new ContainerButton
            {
                MinSize = new Vector2(160, 132),
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                ToolTip = displayName
            };

            var panel = new PanelContainer
            {
                PanelOverride = MakeStyleBox(isSelected ? SelectedBorderColor : DefaultBorderColor),
                MouseFilter = Control.MouseFilterMode.Ignore
            };

            var layout = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                Margin = new Thickness(4),
                MouseFilter = Control.MouseFilterMode.Ignore
            };

            var textureRect = new TextureRect
            {
                Texture = texture,
                MinSize = new Vector2(96, 96),
                HorizontalAlignment = HAlignment.Center,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MouseFilter = Control.MouseFilterMode.Ignore
            };

            var label = new Label
            {
                Text = displayName,
                HorizontalAlignment = HAlignment.Center,
                ClipText = true,
                MaxWidth = 150,
                MouseFilter = Control.MouseFilterMode.Ignore
            };

            layout.AddChild(textureRect);
            layout.AddChild(label);
            panel.AddChild(layout);
            card.AddChild(panel);

            card.OnPressed += _ => OnSpriteChosen?.Invoke(id);

            if (!isSelected)
            {
                card.OnMouseEntered += _ => panel.PanelOverride = MakeStyleBox(HoverBorderColor);
                card.OnMouseExited += _ => panel.PanelOverride = MakeStyleBox(DefaultBorderColor);
            }

            SpriteGrid.AddChild(card);
        }
    }

    private static StyleBoxFlat MakeStyleBox(Color borderColor)
    {
        return new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#1b1b1b"),
            BorderColor = borderColor,
            BorderThickness = new Thickness(2),
            ContentMarginLeftOverride = 4,
            ContentMarginRightOverride = 4,
            ContentMarginTopOverride = 4,
            ContentMarginBottomOverride = 4
        };
    }
}
