# SPDX-FileCopyrightText: 2024 Aiden <aiden@djkraz.com>
# SPDX-FileCopyrightText: 2024 Fishbait <Fishbait@git.ml>
# SPDX-FileCopyrightText: 2024 fishbait <gnesse@gmail.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: antag
  id: Blob
  name: Биомасса # BlackM
  antagonist: true
  setPreference: true
  objective: Образец кристалла из мира "Зен", вызвал катастрофу. Создавайте зен-существ, расширяйтесь и захватите комплекс. Не дайте разрушить ваше сердце.
#  guides: [ Blob ] #BlackM
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 0 # BlackM
  - !type:SpeciesRequirement # CorvaxGoob-Species
    inverted: true
    species:
    - Abductor
