# ================================
# УЧЁНЫЙ
# ================================
- type: startingGear
  id: BmesaScientistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDefaultScienceBmesa
    outerClothing: ClothingOuterCoatHecuScientist
    gloves: ClothingHandsGlovesColorBlack
    shoes: ClothingShoesBootsWinterEngi
    back: ClothingBackpackHecuScience
    id: BmesaResearchPDA
    ears: ClothingHeadsetAltHecuScience
    belt: ClothingBeltUtilityFilled
  storage:
    back:
    - BoxSurvivalSlotsMedical
    - CrowbarRed

# ================================
# НАУЧНЫЙ РУКОВОДИТЕЛЬ
# ================================
- type: startingGear
  id: BmesaResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitHighScienceBmesa
    outerClothing: ClothingOuterCoatHecuScientist
    gloves: ClothingHandsGlovesColorBlack
    shoes: ClothingShoesBootsWinterEngi
    back: ClothingBackpackHecuScience
    id: BmesaResearchDirectorPDA
    ears: ClothingHeadsetAltHecuScience
    belt: ClothingBeltUtilityFilled
  storage:
    back:
    - BoxSurvivalSlotsMedical
    - CrowbarRed

# ================================
# ГОРДОН ФРИМЕН
# ================================
- type: startingGear
  id: GordonFreemanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSecBlue
    outerClothing: ClothingOuterSuitHEV
    shoes: ClothingShoesBootsCombatFilled
    back: ClothingBackpackSatchel
    id: GordonFreemanPDA
    ears: ClothingHeadsetAltHecuScience
    belt: ClothingBeltMercWebbingHelldiverFilled
    suitstorage: WeaponRifleLecter
  storage:
    back:
    - BoxSurvivalSlotsMedical
    - CrowbarRed

# ================================
# ОХРАННИК
# ================================
- type: startingGear
  id: BmesaSecurityGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    outerClothing: ClothingOuterArmorRiot
    head: ClothingHeadHelmetRiot
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesColorBlack
    shoes: ClothingShoesBootsJack
    id: BmesaSecurityPDA
    ears: ClothingHeadsetAltHecuScience
    holster: WeaponPistolMk58