# PlayTimeTracker прототипы
- type: playTimeTracker
  id: JobBmesaResearchDirector

- type: playTimeTracker
  id: JobBmesaScientist

- type: playTimeTracker
  id: JobBmesaSecurity

- type: playTimeTracker
  id: JobGordonFreeman

- type: job
  id: BmesaResearchDirector
  name: job-name-bmesa-research-director
  setPreference: false # Bmesa Roles
  description: job-description-bmesa-research-director
  playTimeTracker: JobBmesaResearchDirector
  weight: 10
  requireAdminNotify: true
  access:
  - Research
  - Command
  - Maintenance
  startingGear: BmesaResearchDirectorGear
  icon: "JobIconBmesaResearchDirector"

- type: job
  id: BmesaScientist
  name: job-name-bmesa-scientist
  setPreference: false # Bmesa Roles
  description: job-description-bmesa-scientist
  playTimeTracker: JobBmesaScientist
  weight: 20
  access:
  - Research
  - Maintenance
  startingGear: BmesaScientistGear
  icon: "JobIconBmesaScientist"

- type: job
  id: BmesaSecurity
  name: job-name-bmesa-security
  setPreference: false # Bmesa Roles
  description: job-description-bmesa-security
  playTimeTracker: JobBmesaSecurity
  weight: 20
  access:
  - Security
  - Maintenance
  startingGear: BmesaSecurityGear
  icon: "JobIconBmesaSecurity"

- type: job
  id: GordonFreeman
  name: job-name-gordon-freeman
  setPreference: false # Bmesa Roles
  description: job-description-gordon-freeman
  playTimeTracker: JobGordonFreeman
  weight: 100
  access:
  - Research
  - Maintenance
  startingGear: GordonFreemanGear
  icon: "JobIconGordonFreeman"