using System.Globalization;
using System.Linq;
using System.Numerics;
using Content.Client.Cargo.Systems;
using Content.Client.Stylesheets;
using Content.Shared.Cargo;
using Content.Shared.Cargo.BUI;
using Content.Shared.Cargo.Components;
using Content.Shared.Cargo.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._BlackM.Cargo.UI;

/// <summary>Client-only catalog, request editor and server-owned order queue.</summary>
[GenerateTypedNameReferences]
public sealed partial class CargoTerminalWindow : BaseWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IResourceCache _resources = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private EntityUid _owner;
    private EntityUid? _station;
    private CargoConsoleInterfaceState? _state;
    private CargoProductPrototype? _selected;
    private string? _category;
    private bool _showApproved;
    private float _refreshElapsed;
    private long _pendingTotal;
    private readonly List<CargoProductPrototype> _products = new();
    private readonly Dictionary<string, CargoTerminalListButton> _productButtons = new();
    private readonly List<(string? Category, CargoTerminalListButton Button)> _categoryButtons = new();
    private readonly List<string?> _categories = new();
    private readonly List<ProtoId<CargoAccountPrototype>> _transferAccounts = new();

    public event Action<string, int, string, string>? OrderSubmitted;
    public event Action<int>? OrderApproved;
    public event Action<int>? OrderCanceled;
    public event Action<ProtoId<CargoAccountPrototype>?, int>? AccountAction;
    public event Action? LimitToggled;

    public CargoTerminalWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        Stylesheet = CargoTerminalStylesheet.Create(_resources);
        MonitorBackground.Texture = Texture("/Textures/_BlackM/Interface/Cargo/monitor.png");
        SearchIcon.Texture = Texture("/Textures/Interface/VerbIcons/examine.svg.192dpi.png");
        SearchIcon.ModulateSelfOverride = StyleNano.TerminalGreen;
        CompactCategories.OptionsScroll.Stylesheet = Stylesheet;
        // OptionButton exposes no clipping setting for its selected label.
        foreach (var label in CompactCategories.Children.SelectMany(child => child.Children).OfType<Label>())
            label.ClipText = true;
        AccountActions.OptionsScroll.Stylesheet = Stylesheet;

        CloseButton.OnPressed += _ => Close();
        CatalogTab.OnPressed += _ => ShowFunds(false);
        FundsTab.OnPressed += _ => ShowFunds(true);
        SearchBar.OnTextChanged += _ => PopulateProducts();
        CompactCategories.OnItemSelected += args => SelectCategory(_categories[args.Id]);
        PendingTab.OnPressed += _ => ShowOrders(false);
        ApprovedTab.OnPressed += _ => ShowOrders(true);
        Amount.InitDefaultButtons();
        Amount.IsValid = amount => amount > 0 && amount <= (_state?.Capacity ?? 1);
        Amount.ValueChanged += _ => UpdateSelection();
        SubmitButton.OnPressed += _ => SubmitOrder();
        TransferAmount.InitDefaultButtons();
        TransferAmount.IsValid = amount => amount >= 0;
        AccountActions.OnItemSelected += args => AccountActions.SelectId(args.Id);
        TransferButton.OnPressed += _ => TransferFunds();
        LimitButton.OnPressed += _ => LimitToggled?.Invoke();
        OnOpen += FitToScreen;
        FitToScreen();
    }

    /// <summary>Associates the view with its console and the local requester's identity.</summary>
    public void Initialize(EntityUid owner, string requester)
    {
        _owner = owner;
        Requester.Text = requester;
        FitToScreen();
        UpdateAccount();
    }

    /// <summary>Applies the authoritative catalog and orders without losing the draft or filters.</summary>
    public void UpdateState(CargoConsoleInterfaceState state)
    {
        _state = state;
        _station = _entity.GetEntity(state.Station);
        _products.Clear();
        var allowed = _entity.GetComponentOrNull<CargoOrderConsoleComponent>(_owner)?.AllowedGroups;
        foreach (var id in state.Products)
        {
            if (_prototype.TryIndex(id, out var product) && (allowed == null || allowed.Contains(product.Group)))
                _products.Add(product);
        }

        _products.Sort((left, right) => string.Compare(left.Name, right.Name, StringComparison.CurrentCultureIgnoreCase));
        if (_selected != null)
            _selected = _products.Find(product => product.ID == _selected.ID);

        PopulateCategories();
        PopulateProducts();
        PopulateOrders();
        if (Amount.Value > state.Capacity && state.Capacity > 0)
            Amount.Value = state.Capacity;
        UpdateSelection();
        UpdateAccount();
    }

    private void PopulateCategories()
    {
        CategoryList.DisposeAllChildren();
        CompactCategories.Clear();
        _categoryButtons.Clear();
        _categories.Clear();
        _categories.Add(null);
        var categories = _products.Select(product => product.Category.ToString()).Where(category => !string.IsNullOrWhiteSpace(category)).Distinct().ToList();
        categories.Sort((left, right) => string.Compare(Loc.GetString(left), Loc.GetString(right), StringComparison.CurrentCultureIgnoreCase));
        _categories.AddRange(categories);
        if (!_categories.Contains(_category))
            _category = null;

        for (var i = 0; i < _categories.Count; i++)
        {
            var category = _categories[i];
            var name = category == null ? Loc.GetString("cargo-console-menu-populate-categories-all-text") : Loc.GetString(category);
            var button = new CargoTerminalListButton(name, arrow: Texture("/Textures/Interface/Nano/triangle_right.png"))
                { Pressed = category == _category, ToolTip = name };
            button.OnPressed += _ => SelectCategory(category);
            CategoryList.AddChild(button);
            _categoryButtons.Add((category, button));
            CompactCategories.AddItem(name, i);
        }
        CompactCategories.SelectId(_categories.IndexOf(_category));
    }

    private void SelectCategory(string? category)
    {
        _category = category;
        foreach (var (id, button) in _categoryButtons)
            button.Pressed = id == category;
        CompactCategories.SelectId(_categories.IndexOf(category));
        CompactCategories.ToolTip = category == null ? Loc.GetString("cargo-console-menu-populate-categories-all-text") : Loc.GetString(category);
        PopulateProducts();
    }

    private void PopulateProducts()
    {
        ProductList.DisposeAllChildren();
        _productButtons.Clear();
        var search = SearchBar.Text.Trim();
        foreach (var product in _products)
        {
            if (_category != null && product.Category.ToString() != _category)
                continue;
            if (search.Length != 0 && !product.Name.Contains(search, StringComparison.CurrentCultureIgnoreCase)
                                   && !product.Description.Contains(search, StringComparison.CurrentCultureIgnoreCase))
                continue;

            var button = new CargoTerminalListButton(product.Name, _entity.System<SpriteSystem>().Frame0(product.Icon), Money(product.Cost))
            {
                ToolTip = product.Name + "\n" + product.Description,
                Pressed = _selected?.ID == product.ID,
                HorizontalExpand = true,
            };
            button.OnPressed += _ => SelectProduct(product);
            ProductList.AddChild(button);
            _productButtons[product.ID] = button;
        }
        NoProductsLabel.Visible = _productButtons.Count == 0;
    }

    private void SelectProduct(CargoProductPrototype product)
    {
        _selected = product;
        foreach (var (id, button) in _productButtons)
            button.Pressed = id == product.ID;
        UpdateSelection();
    }

    private void UpdateSelection()
    {
        ProductNameLabel.Text = _selected?.Name ?? Loc.GetString("blackm-cargo-select-product");
        ProductNameLabel.ToolTip = _selected?.Name;
        ProductDescriptionLabel.Text = _selected?.Description ?? string.Empty;
        ProductDescriptionLabel.ToolTip = _selected?.Description;
        ProductIcon.Texture = _selected == null ? null : _entity.System<SpriteSystem>().Frame0(_selected.Icon);
        SelectedTotalLabel.Text = Loc.GetString("blackm-cargo-selected-total", ("amount", Money((long) (_selected?.Cost ?? 0) * Amount.Value)));
        SubmitButton.Disabled = _selected == null || _state == null || Amount.Value < 1 || Amount.Value > _state.Capacity;
    }

    private void SubmitOrder()
    {
        if (_selected == null || _state == null || Amount.Value < 1 || Amount.Value > _state.Capacity)
            return;
        OrderSubmitted?.Invoke(_selected.ID, Amount.Value, Requester.Text, Reason.Text);
    }

    private void ShowOrders(bool approved)
    {
        _showApproved = approved;
        PendingTab.Pressed = !approved;
        ApprovedTab.Pressed = approved;
        PopulateOrders();
    }

    private void PopulateOrders()
    {
        OrderList.DisposeAllChildren();
        _pendingTotal = 0;
        if (_state == null || !_entity.TryGetComponent<CargoOrderConsoleComponent>(_owner, out var console))
            return;

        var shown = 0;
        foreach (var order in _state.Orders)
        {
            if (!order.Approved && order.Account == console.Account)
                _pendingTotal += (long) order.Price * order.OrderQuantity;
            if (order.Approved != _showApproved)
                continue;
            shown++;
            var productName = _prototype.TryIndex<EntityPrototype>(order.ProductId, out var product) ? product.Name : order.ProductName;
            var account = _prototype.Index(order.Account);
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 3 };
            row.AddChild(new Label { Text = productName, ClipText = true, ToolTip = productName });
            var meta = Loc.GetString("blackm-cargo-order-meta", ("id", order.OrderId),
                ("account", Loc.GetString(account.Code)), ("requester", order.Requester));
            row.AddChild(new Label { Text = meta, ClipText = true, ToolTip = meta + "\n" + order.Reason, StyleClasses = { "TerminalMuted" } });
            var actions = new BoxContainer { SeparationOverride = 4 };
            actions.AddChild(new Label
            {
                Text = Loc.GetString("blackm-cargo-order-amount", ("quantity", order.OrderQuantity), ("amount", Money((long) order.Price * order.OrderQuantity))),
                HorizontalExpand = true,
                ClipText = true,
            });
            if (!order.Approved)
            {
                if (console.Mode == CargoOrderConsoleMode.DirectOrder)
                {
                    var approve = IconButton("/Textures/Interface/Nano/checkbox_checked.svg.96dpi.png", "blackm-cargo-approve");
                    approve.OnPressed += _ => OrderApproved?.Invoke(order.OrderId);
                    actions.AddChild(approve);
                }
                var cancel = IconButton("/Textures/Interface/Nano/cross.svg.png", "blackm-cargo-cancel");
                cancel.OnPressed += _ => OrderCanceled?.Invoke(order.OrderId);
                actions.AddChild(cancel);
            }
            row.AddChild(actions);
            if (order.Approved)
                row.AddChild(new Label { Text = Loc.GetString("blackm-cargo-dispatched", ("count", order.NumDispatched), ("quantity", order.OrderQuantity)), ClipText = true });
            row.AddChild(new PanelContainer { SetHeight = 1, StyleClasses = { "TerminalRule" } });
            OrderList.AddChild(row);
        }
        NoOrdersLabel.Visible = shown == 0;
        PendingTotalLabel.Text = Money(_pendingTotal);
        CapacityLabel.Text = Loc.GetString("blackm-cargo-capacity", ("count", _state.Count), ("capacity", _state.Capacity));
    }

    private void ShowFunds(bool funds)
    {
        CatalogTab.Pressed = !funds;
        FundsTab.Pressed = funds;
        CatalogPage.Visible = !funds;
        FundsPage.Visible = funds;
        UpdateAccount();
    }

    private void UpdateAccount()
    {
        if (!_entity.TryGetComponent<CargoOrderConsoleComponent>(_owner, out var console))
            return;

        var account = _prototype.Index(console.Account);
        AccountLabel.Text = Loc.GetString(account.Name);
        AccountLabel.ToolTip = AccountLabel.Text;
        var printing = console.Mode == CargoOrderConsoleMode.PrintSlip;
        OrderColumn.Visible = !printing;
        OrderDivider.Visible = !printing;
        SubmitButton.Text = Loc.GetString(console.Mode switch
        {
            CargoOrderConsoleMode.PrintSlip => "blackm-cargo-print",
            CargoOrderConsoleMode.SendToPrimary => "blackm-cargo-forward",
            _ => "blackm-cargo-submit",
        });

        if (!_entity.TryGetComponent<StationBankAccountComponent>(_station, out var bank))
        {
            StatusLabel.Text = Loc.GetString("blackm-cargo-disconnected");
            TransferButton.Disabled = true;
            return;
        }

        var balance = _entity.System<CargoSystem>().GetBalanceFromAccount((_station.Value, bank), console.Account);
        BalanceLabel.Text = Loc.GetString("blackm-cargo-balance", ("amount", Money(balance)));
        RemainingLabel.Text = Money(balance - _pendingTotal);
        StatusLabel.Text = Loc.GetString("blackm-cargo-connected");
        var limit = (int) Math.Floor(balance * console.TransferLimit);
        TransferLimitLabel.Text = Loc.GetString("blackm-cargo-transfer-limit", ("amount", Money(limit)));
        UnlimitedLabel.Visible = console.TransferUnbounded;
        TransferButton.Disabled = TransferAmount.Value <= 0 || TransferAmount.Value > limit || _timing.CurTime < console.NextAccountActionTime;

        var accounts = bank.Accounts.Keys.Where(id => id != console.Account).OrderBy(id => id.Id).ToList();
        if (!_transferAccounts.SequenceEqual(accounts) || AccountActions.ItemCount == 0)
        {
            var selected = AccountActions.ItemCount > 0 ? AccountActions.SelectedMetadata : null;
            _transferAccounts.Clear();
            _transferAccounts.AddRange(accounts);
            AccountActions.Clear();
            AccountActions.AddItem(Loc.GetString("cargo-console-menu-account-action-option-withdraw"), 0);
            for (var i = 0; i < accounts.Count; i++)
            {
                var target = _prototype.Index(accounts[i]);
                AccountActions.AddItem(Loc.GetString("cargo-console-menu-account-action-option-transfer", ("code", Loc.GetString(target.Code))), i + 1);
                AccountActions.SetItemMetadata(i + 1, accounts[i]);
            }
            var selectedIndex = selected is ProtoId<CargoAccountPrototype> id ? accounts.IndexOf(id) + 1 : 0;
            AccountActions.SelectId(Math.Max(0, selectedIndex));
        }
    }

    private void TransferFunds()
    {
        UpdateAccount();
        if (!TransferButton.Disabled)
            AccountAction?.Invoke((ProtoId<CargoAccountPrototype>?) AccountActions.SelectedMetadata, TransferAmount.Value);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _refreshElapsed += args.DeltaSeconds;
        if (_refreshElapsed < 0.25f)
            return;
        _refreshElapsed = 0;
        UpdateAccount();
    }

    private void FitToScreen()
    {
        var available = UserInterfaceManager.WindowRoot.Size - new Vector2(24, 24);
        if (available.X <= 0 || available.Y <= 0)
            return;
        SetSize = Vector2.Min(new Vector2(1180, 720), available);
        MinSize = Vector2.Min(new Vector2(640, 420), available);
        UpdateScreenMargins(SetSize);
        Measure(available);
    }

    protected override void Resized()
    {
        base.Resized();
        UpdateScreenMargins(Size);
    }

    private void UpdateScreenMargins(Vector2 size)
    {
        if (ScreenArea == null)
            return;
        ScreenBacking.Margin = new Thickness(size.X * 0.04f, size.Y * 0.06f, size.X * 0.04f, size.Y * 0.10f);
        ScreenArea.Margin = new Thickness(size.X * 0.065f, size.Y * 0.09f, size.X * 0.065f, size.Y * 0.15f);
        CategoryColumn.Visible = size.X >= 900;
        CategoryDivider.Visible = CategoryColumn.Visible;
        CompactCategories.Visible = !CategoryColumn.Visible;
        Footer.Visible = size.Y >= 500;
        FooterDivider.Visible = Footer.Visible;
        ProductDetails.Visible = size.Y >= 500;
    }

    private Texture Texture(string path) => _resources.GetResource<TextureResource>(path).Texture;

    private ContainerButton IconButton(string path, string tooltip)
    {
        var button = new ContainerButton { SetSize = new Vector2(30, 28), ToolTip = Loc.GetString(tooltip) };
        button.AddChild(new TextureRect
        {
            Texture = Texture(path), SetSize = new Vector2(16, 16), Stretch = TextureRect.StretchMode.KeepAspectCentered,
            HorizontalAlignment = HAlignment.Center, VerticalAlignment = VAlignment.Center,
            ModulateSelfOverride = StyleNano.TerminalGreen,
        });
        return button;
    }

    protected override DragMode GetDragModeFor(Vector2 position)
    {
        var mode = DragMode.None;
        if (Resizable)
        {
            if (position.X < 6) mode |= DragMode.Left;
            else if (position.X > Size.X - 6) mode |= DragMode.Right;
            if (position.Y < 6) mode |= DragMode.Top;
            else if (position.Y > Size.Y - 6) mode |= DragMode.Bottom;
        }
        return mode != DragMode.None ? mode : position.Y < 55 ? DragMode.Move : DragMode.None;
    }

    private static string Money(long amount) => amount.ToString("N0", CultureInfo.CurrentCulture);
}
